#########################
#       HTTP code
#########################

[200.HTTPcode]
name = "HTTP response status code: 200"
desc = "OK"

[201.HTTPcode]
name = "HTTP response status code: 201"
desc = "Created"

[301.HTTPcode]
name = "HTTP response status code: 301"
desc = "Moved Permanently"

[302.HTTPcode]
name = "HTTP response status code: 302"
desc = "Found"
see = ['404']

[303.HTTPcode]
name = "HTTP response status code: 303"
desc = "See Other"

[307.HTTPcode]
name = "HTTP response status code: 307"
desc = "Temporary Redirect"

[308.HTTPcode]
name = "HTTP response status code: 308"
desc = "Permanent Redirect"

[400.HTTPcode]
name = "HTTP response status code: 400"
desc = "Bad Request"

[403.HTTPcode]
name = "HTTP response status code: 403"
desc = "Forbidden"

[404.HTTPcode]
name = "HTTP response status code: 404"
desc = "Not Found"
see = ['302']

[500.HTTPcode]
name = "HTTP response status code: 500"
desc = "Internal Server Error"

[502.HTTPcode]
name = "HTTP response status code: 502"
desc = "Bad Gateway"

[503.HTTPcode]
name = "HTTP response status code: 503"
desc = "Service Unavailable"

#########################
#         Port
#########################

[22.port]
name = "port 22"
more = "SSH default port"

[53.port]
name = "port 53"
more = "DNS used for domain name resolution"

[443.port]
name = "port 443"
desc = "HTTPS Port"

#########################
#         IEEE
#########################

[1394.IEEE]
name = "IEEE 1394"
more = """An interface standard for a serial bus for high-speed communications and isochronous real-time data transfer. It was developed in the late 1980s and early 1990s by Apple in cooperation with a number of companies, primarily Sony and Panasonic. 

  The 1394 interface is comparable to USB. USB was developed subsequently and gained much greater market share. USB requires a host controller whereas IEEE 1394 is cooperatively managed by the connected devices"""


#########################
#         ISO
#########################

[639.ISO]
name = "ISO 639"
desc = "Language Codes"

[3166.ISO]
name = "ISO 3166"
more = "Country Codes"

[4217.ISO]
name = "ISO 4217"
more = "It defines alpha codes and numeric codes for the representation of currencies and provides information about the relationships between individual currencies and their minor units"

[8859.ISO]
name = "ISO/IEC 8859"
more = "A joint ISO and IEC series of standards for 8-bit character encodings"

[9001.ISO]
name = "ISO 9001"
more = "The internationally recognized standard for Quality Management Systems"

[10646.ISO]
name = "ISO/IEC 10646"
more = "A standard set of characters —— The Universal Coded Character Set (UCS, Unicode)"

[30170.ISO]
name = "ISO/IEC 30170:2012"
desc = "Information technology — Programming languages — Ruby"


#########################
#         RFC
#########################

[1321.RFC]
name = "RFC 1321"
desc = "The MD5 Message-Digest Algorithm"

[2119.RFC]
name = "RFC 2119"
desc = "Key words for use in RFCs to Indicate Requirement Levels"

[3339.RFC]
name = "RFC 3339"
desc = "Date and Time on the Internet: Timestamps"


#########################
#         Other
#########################

[2fa]
name = "2FA"
desc = "Two-factor Authentication"
see = ['MFA']

[3c]
name = "3C"
desc = "computer, communication, consumer"
