[0.fd]
name = "0(Linux)"
desc = "standard input"

[1.fd]
name = "1(Linux)"
desc = "standard output"

[2.fd]
name = "2(Linux)"
desc = "standard error"

[1.man]
name = "man 1"
desc = "Executable programs or shell commands"

[2.man]
name = "man 2"
desc = "System calls"

[3.man]
name = "man 3"
desc = "Library calls"

[4.man]
name = "man 4"
desc = "Special files"

[5.man]
name = "man 5"
desc = "File formats and conventions"

[6.man]
name = "man 6"
desc = "Games"

[7.man]
name = "man 7"
desc = "Miscellaneous"

[8.man]
name = "man 8"
desc = "System administration commands"

[9.man]
name = "man 9"
desc = "Kernel routines"

[2fa]
name = "2FA"
desc = "Two-factor Authentication"
see = ['MFA']

[200.HTTPcode]
name = "HTTP response status code: 200"
desc = "OK"

[201.HTTPcode]
name = "HTTP response status code: 201"
desc = "Created"

[301.HTTPcode]
name = "HTTP response status code: 301"
desc = "Moved Permanently"

[302.HTTPcode]
name = "HTTP response status code: 302"
desc = "Found"
see = ['404']

[308.HTTPcode]
name = "HTTP response status code: 308"
desc = "Permanent Redirect"

[400.HTTPcode]
name = "HTTP response status code: 400"
desc = "Bad Request"

[403.HTTPcode]
name = "HTTP response status code: 403"
desc = "Forbidden"

[404.HTTPcode]
name = "HTTP response status code: 404"
desc = "Not Found"
see = ['302']

[443.port]
name = "443 port"
desc = "HTTPS Port"

[500.HTTPcode]
name = "HTTP response status code: 500"
desc = "Internal Server Error"

[502.HTTPcode]
name = "HTTP response status code: 502"
desc = "Bad Gateway"

#########################
#         ISO
#########################

[639.ISO]
name = "ISO 639"
desc = "Language Codes"

[3166.ISO]
name = "ISO 3166"
more = "Country Codes"

[4217.ISO]
name = "ISO 4217"
more = "It defines alpha codes and numeric codes for the representation of currencies and provides information about the relationships between individual currencies and their minor units"

[30170.ISO]
name = "ISO/IEC 30170:2012"
desc = "Information technology — Programming languages — Ruby"


#########################
#         RFC
#########################

[1321.RFC]
name = "RFC 1321"
desc = "The MD5 Message-Digest Algorithm"


[3c]
name = "3C"
desc = "computer, communication, consumer"
