[alsa]
name = "alsa"
desc = "Advanced Linux Sound Architecture"

[apm]
name = "APM"
desc = "Application performance management"

[abnf]
name = "ABNF"
desc = "Augmented Backus–Naur form"

[avi]
name = "AVI"
desc = "Audio Video Interleave"
more = "Introduced by Microsoft in November 1992 as part of its Video for Windows software"

[avc]
name = "AVC"
desc = "Advanced Video Coding"
more = "Known as H.264 introduced in 2003"

[aac]
name = "AAC"
desc = "Advanced Audio Coding"

[adi]
name = "ADI"
desc = "Analog Devices Inc"

[amd]
name = "AMD"
desc = "Advanced Micro Devices"

[aoe]
name = "AOE"
desc = "Activity On Edge network"

[ami]
name = "AMI"
desc = "Amazon Machine Images"

[awk]
name = "awk language"
desc = "Alfred Aho, Peter Weinberger,and Brian Kernighan"

[ansi]
name = "ANSI"
desc = "American National Standards Institute"

[alisp]
name = "ALisp"
desc = "AutoLisp"

[asdf]
name = "ASDF"
desc = "Another System Definition Facility"
more = "a build tool for Common Lisp libraries. It is analogous to tools such as Make and Ant."

[atk]
name = "ATK"
desc = "Accessibility Toolkit"

[abcl]
name = "ABCL"
desc = "Armed Bear Common Lisp"
more = "Common Lisp in the JVM"

[armhf]
name = "armhf"
desc = "ARM hard float"

[armel]
name = "armel"
desc = "ARM Embedded ABI"

[aes]
name = "AES"
desc = "Advanced Encryption Standard"

[ar]
name = "AR"
desc = "Augmented Reality"

[amoled]
name = "AMOLED"
desc = "Active-Matrix Organic Light-Emitting Diode"

[arm]
name = "ARM"
desc = "Advanced RISC Machines and originally Acorn RISC Machine"

[arm.'C++']
name = "ARM"
desc = "The Annotated C++ Reference Manual"

[acme]
name = "ACME"
desc = "Automated Certificate Management Environment"

[ado]
name = "ADO"
desc = "ActiveX Data Objects"

[ascii]
name = "ASCII"
desc = "American Standard Code for Information Interchange"

[avr]
name = "AVR"
desc = "Alf and Vegard's RISC processor."
more = "A family of microcontrollers developed since 1996 by Atmel"

[adc]
name = "ADC"
desc = "Analog To Digital Converter"

[alm]
name = "ALM"
desc = "Application Lifecycle Management"

[aot]
name = "AOT"
desc = "Ahead-of-Time Compilation"
see = ['JIT']

[ast]
name = "AST"
desc = "Abstract Syntax Tree"

[aosp]
name = "AOSP"
desc = "Android Open Source Project"

[alb]
name = "ALB"
desc = "AWS Load Balances"

[aws]
name = "AWS"
desc = "Amazon Web Services"

[apt.debian]
name = "APT"
desc = "Advanced Package Tool"

[apt]
name = "APT"
desc = "Advanced Persistent Threat"

[acm]
name = "ACM"
desc = "Association for Computing Machinery"

[apkg.anki]
name = ".apkg"
desc = "Anki Deck Pakcage"

[anki]
name = "Anki"
desc = "Anki (暗記) is the Japanese word for 'memorization'"
more = "A free and open-source flashcard program using spaced repetition"

[ata]
name = "ATA"
desc = "AT Attachment"
more = "Standard interface designed for IBM PC-compatible computers. It was first developed by Western Digital and Compaq in 1986 for compatible hard drives and CD or DVD drives."
see = ['IDE', 'PATA', 'SATA']

[atapi]
name = "ATAPI"
desc = "ATA Packet Interface"
see = ['ATA']

[adsl]
name = "ADSL"
desc = "Asymmetric Digital Subscriber Line"
see = ['DSL']

[asic]
name = "ASIC"
desc = "Application-Specific Integrated Circuit"
see = ['ASSP']

[assp]
name = "ASSP"
desc = "Application-Specific Standard Product"
see = ['ASIC']

[api]
name = "API"
desc = "Application Programming Interface"

[ai]
name = "AI"
desc = "Artificial Intelligence"

[adt]
name = "ADT"
desc = "Abstract Data Type"

[antlr]
name = "ANTLR"
desc = "ANother Tool for Language Recognition"

[apl]
name = "APL"
desc = "named after the book A Programming Language"
more = "A programming language developed in the 1960s by Kenneth E. Iverson"

# Can't match it on terminal input
["at&t"]
name = "AT&T"
desc = "American Telephone and Telegraph Company"

[att]
same = "AT&T=>at&t"

[ampl]
name = "AMPL"
desc = "A Mathematical Programming Language"
more = "An algebraic modeling language to describe and solve high-complexity problems for large-scale mathematical computing (i.e., large-scale optimization and scheduling-type problems). It was developed by Robert Fourer, David Gay, and Brian Kernighan at Bell Laboratories. "

[ace]
name = "ACE"
desc = "Automatic Computing Engine"
more = "A British early electronic serial stored-program computer designed by Alan Turing"

[algol]
name = "ALGOL"
desc = "Algorithmic Language"

[acpi]
name = "ACPI"
desc = "Advanced Configuration and Power Interface"

[arp]
name = "ARP"
desc = "Address Resolution Protocol"

[asf]
name = "ASF"
desc = "Apache Software Foundation"

[av1]
name = "AV1"
desc = "AOMedia Video 1"
more = "An open, royalty-free video coding format initially designed for video transmissions over the Internet. It was developed as a successor to VP9 by (AOMedia)"
see = ['VP9']

[aomedia]
name = "AOMedia"
desc = "Alliance for Open Media"
more = "A consortium founded in 2015 that includes semiconductor firms, video on demand providers, video content producers, software development companies and web browser vendors"

[aur]
name = "AUR"
desc = "Arch User Repository"

[aoc]
name = "AoC"
desc = "Advent of Code"
more = "https://adventofcode.com/"

[ams.Android]
name = "AMS"
desc = "Activity Manager Service"
more = "System process provided by Android to manage the running status of Activity and other components"

[aop]
name = "AOP"
desc = "Aspect-Oriented Programming"

[asm.Java]
name = "ASM"
desc = "assembly"
more = ''' It provides a simple API for decomposing, modifying, and recomposing binary Java classes (i.e. bytecode). The project was originally conceived and developed by Eric Bruneton. ASM is Java-centric at present, and does not currently have a backend that exposes other bytecode implementations (such as .NET bytecode, Python bytecode, etc.).

  The name "ASM" is not an acronym: it is just a reference to the asm keyword of C, which allows some functions to be implemented in assembly language.'''

[agpl]
name = "AGPL"
desc = "Affero General Public License"

[abs.Arch]
name = "ABS"
desc = "Arch Build System"

[alg.Arch]
name = "ALG"
desc = "Arch Linux GUI project"

[asplos]
name = "ASPLOS"
desc = "Architectural Support for Programming Languages and Operating Systems"

[amba]
name = "AMBA"
desc = "The ARM Advanced Microcontroller Bus Architecture"

[apu]
name = "APU"
desc = "Accelerated Processing Unit"
more = "Combine the CPU and GPU onto a single die"

[acl]
name = "ACL"
desc = "Access Control Lists"

[afl]
name = "AFL"
desc = "American Fuzzy Lop"
more = "A security-oriented fuzzer by Google"

[atdd]
name = "ATDD"
desc = "Acceptance Test–Driven Development"

[ast.secure]
name = "AST"
desc = "Application Security Testing"

[adas]
name = "ADAS"
desc = "Advanced Driver Assistance Systems"

[ac]
name = "AC"
desc = "Alternating Current"
see = 'DC'

[atx]
name = "ATX"
desc = "Advanced Technology eXtended"
more = "A motherboard and power supply configuration specification developed by Intel in 1995 to improve on previous de facto standards like the AT design"

[agp]
name = "AGP"
desc = "Accelerated Graphics Port"
more = "Since 2004, AGP was progressively phased out in favor of PCI Express (PCIe), which is serial, as opposed to parallel"

[autosar]
name = "AUTOSAR"
desc = "AUTomotive Open System ARchitecture"
more = "A development partnership of automotive interested parties founded in 2003. It pursues the objective to create and establish an open and standardized software architecture for automotive electronic control units (ECUs)"

[adb]
name = "adb"
desc = "Android Debug Bridge"

[at]
name = "IBM AT"
desc = "IBM PC Advanced Technology"
see = ['XT','PS/2']

[apic]
name = "APIC"
desc = "Advanced Programmable Interrupt Controller"
more = "The updated Intel standard for the older PIC"
see = 'PIC'

[aigc]
name = "AIGC"
desc = "AI-Generated Content"

[avl]
name = "AVL tree"
desc = "Adelson-Velsky and Landis"
more = "An AVL tree is a self-balancing binary search tree. It was the first such data structure to be invented."

[astyle]
name = "astyle"
desc = "Artistic Style"
more = """A source code indenter, formatter and beautifier, written in C++. It handles the following programming languages: C, C++, C++/CLI, Objective-C, C#, Java.

  Visit: https://astyle.sourceforge.net
"""
