[alsa]
disp = "alsa"
desc = "Advanced Linux Sound Architecture"

[apm]
disp = "APM"
desc = "Application performance management"

[abnf]
disp = "ABNF"
desc = "Augmented Backusâ€“Naur form"

[avi]
disp = "AVI"
desc = "Audio Video Interleave"
full = "Introduced by Microsoft in November 1992 as part of its Video for Windows software"

[avc]
disp = "AVC"
desc = "Advanced Video Coding"
full = "Known as H.264 introduced in 2003"

[aac]
disp = "AAC"
desc = "Advanced Audio Coding"

[adi]
disp = "ADI"
desc = "Analog Devices Inc"

[amd]
disp = "AMD"
desc = "Advanced Micro Devices"

[aoe]
disp = "AOE"
desc = "Activity On Edge network"

[avx]
disp = "AVX"
desc = "Advanced Vector Extensions"
full = "Intel chips support"

[ami]
disp = "AMI"
desc = "Amazon Machine Images"

[awk]
disp = "awk language"
desc = "Alfred Aho, Peter Weinberger,and Brian Kernighan"

[ansi]
disp = "ANSI"
desc = "American National Standards Institute"

[alisp]
disp = "ALisp"
desc = "AutoLisp"

[asdf]
disp = "ASDF"
desc = "Another System Definition Facility"
full = "a build tool for Common Lisp libraries. It is analogous to tools such as Make and Ant."

[atk]
disp = "ATK"
desc = "Accessibility Toolkit"

[abcl]
disp = "ABCL"
desc = "Armed Bear Common Lisp"
full = "Common Lisp in the JVM"

[armhf]
disp = "armhf"
desc = "ARM hard float"

[armel]
disp = "armel"
desc = "ARM Embedded ABI"

[aes]
disp = "AES"
desc = "Advanced Encryption Standard"

[ar]
disp = "AR"
desc = "Augmented Reality"

[atl]
disp = "ATL"
desc = "Active Template Library"

[amoled]
disp = "AMOLED"
desc = "Active-Matrix Organic Light-Emitting Diode"

[arm]
disp = "ARM"
desc = "Advanced RISC Machines and originally Acorn RISC Machine"

[acme]
disp = "ACME"
desc = "Automated Certificate Management Environment"

[ado]
disp = "ADO"
desc = "ActiveX Data Objects"

[ascii]
disp = "ASCII"
desc = "American Standard Code for Information Interchange"

[avr]
disp = "AVR"
desc = "Help!"
full = "A family of microcontrollers developed since 1996 by Atmel"

[adc]
disp = "ADC"
desc = "Analog To Digital Converter"

[alm]
disp = "ALM"
desc = "Application Lifecycle Management"

[aot]
disp = "AOT"
desc = "Ahead-of-Time Compilation"
see = ['JIT']

[ast]
disp = "AST"
desc = "Abstract Syntax Tree"

[aosp]
disp = "AOSP"
desc = "Android Open Source Project"

[alb]
disp = "ALB"
desc = "AWS Load Balances"

[aws]
disp = "AWS"
desc = "Amazon Web Services"

[apt.debian]
disp = "APT"
desc = "Advanced Package Tool"

[apt]
disp = "APT"
desc = "Advanced Persistent Threat"
