[alsa]
disp = "alsa"
desc = "Advanced Linux Sound Architecture"

[apm]
disp = "APM"
desc = "Application performance management"

[abnf]
disp = "ABNF"
desc = "Augmented Backusâ€“Naur form"

[avi]
disp = "AVI"
desc = "Audio Video Interleave"
full = "Introduced by Microsoft in November 1992 as part of its Video for Windows software"

[avc]
disp = "AVC"
desc = "Advanced Video Coding"
full = "Known as H.264 introduced in 2003"

[aac]
disp = "AAC"
desc = "Advanced Audio Coding"

[adi]
disp = "ADI"
desc = "Analog Devices Inc"

[amd]
disp = "AMD"
desc = "Advanced Micro Devices"

[aoe]
disp = "AOE"
desc = "Activity On Edge network"

[avx]
disp = "AVX"
desc = "Advanced Vector Extensions"
full = "Intel chips support"

[ami]
disp = "AMI"
desc = "Amazon Machine Images"

[awk]
disp = "awk language"
desc = "Alfred Aho, Peter Weinberger,and Brian Kernighan"

[ansi]
disp = "ANSI"
desc = "American National Standards Institute"

[alisp]
disp = "ALisp"
desc = "AutoLisp"

[asdf]
disp = "ASDF"
desc = "Another System Definition Facility"
full = "a build tool for Common Lisp libraries. It is analogous to tools such as Make and Ant."

[atk]
disp = "ATK"
desc = "Accessibility Toolkit"

[abcl]
disp = "ABCL"
desc = "Armed Bear Common Lisp"
full = "Common Lisp in the JVM"

[armhf]
disp = "armhf"
desc = "ARM hard float"

[armel]
disp = "armel"
desc = "ARM Embedded ABI"

[aes]
disp = "AES"
desc = "Advanced Encryption Standard"

[ar]
disp = "AR"
desc = "Augmented Reality"
