[BMP]
desc = "Bitmap image file"
full = "Developed by Microsoft in 1986? used RLE lossless data compression algorithm"

[blob]
desc = "Binary Large OBject"

[BOM]
desc = "byte order mark"

[BJT]
desc = "Bipolar Junction Transistor"

[BCPL]
desc = "Basic Combined Programming Language"