[bmp.image]
disp = "BMP"
desc = "Bitmap image file"
full = "Developed by Microsoft in 1986? used RLE lossless data compression algorithm"

[blob]
disp = "blob"
desc = "Binary Large OBject"

[bom]
disp = "BOM"
desc = "byte order mark"

[bjt]
disp = "BJT"
desc = "Bipolar Junction Transistor"

[bcpl]
disp = "BCPL"
desc = "Basic Combined Programming Language"

[blas]
disp = "BLAS"
desc = "Basic Linear Algebra Subprograms"

[bpmn]
disp = "BPMN"
desc = "Business Process Model and Notation"

[bmp.unicode]
disp = "BMP"
desc = "Basic Multilingual Plane"
full = "range U+0000â€”U+FFFF"

[ble]
disp = "BLE"
desc = "Bluetooth Low Energy"

[bsod]
disp = "BSOD"
desc = "Blue Screen of Death"

[bpf]
disp = "BPF"
desc = "Berkeley Packet Filter"
