[bmp.image]
disp = "BMP"
desc = "Bitmap image file"
full = "Developed by Microsoft in 1986? used RLE lossless data compression algorithm"

[blob]
disp = "blob"
desc = "Binary Large OBject"

[bom]
disp = "BOM"
desc = "byte order mark"

[bjt]
disp = "BJT"
desc = "Bipolar Junction Transistor"

[bcpl]
disp = "BCPL"
desc = "Basic Combined Programming Language"

[blas]
disp = "BLAS"
desc = "Basic Linear Algebra Subprograms"

[bpmn]
disp = "BPMN"
desc = "Business Process Model and Notation"

[bmp.unicode]
disp = "BMP"
desc = "Basic Multilingual Plane"
full = "range U+0000—U+FFFF"

[ble]
disp = "BLE"
desc = "Bluetooth Low Energy"

[bsod]
disp = "BSOD"
desc = "Blue Screen of Death"

[bpf]
disp = "BPF"
desc = "Berkeley Packet Filter"

[bnf]
disp = "BNF"
desc = "Backus–Naur Form"

[bcd]
same = "BCDIC"
# Fixme!!! here should be [bcd.ibm] when program has been fixed

[bcdic]
disp = "BCDIC"
desc = "Binary-Coded Decimal Interchange Code"
full = "6-bit alphanumeric codes that represented numbers, upper-case letters and special characters. "
see = ['EBCDIC']
