[cups]
disp = "CUPS"
desc = "Common Unix Printing System"

[cst.America]
disp = "CST(America)"
desc = "Central Standard Time(UTC-6)"
see = ['UTC']

[cst.China]
disp = "CST(China)"
desc = "China Standard Time(UTC+8)"

[crt.electronics]
disp = "CRT"
desc = "Cathode Ray Tube"

[csrf]
disp = "CSRF"
desc = "Cross Site Request Forgery"

[cur]
disp = "CUR"
desc = "Cursor image format for Windows"
see = ["ICO"]

[com]
disp = "COM"
desc = "Component Object Model"
full = "A binary-interface standard for software components introduced by Microsoft in 1993. It is used to enable inter-process communication object creation in a large range of programming languages"

[csp]
disp = "CSP"
desc = "Communicating Sequential Processs"

[cpl]
disp = "cpl"
desc = "Control PaneL"
full = "Control panel tools for Windows"

[cuda]
disp = "CUDA"
desc = "Compute Unified Device Architecture"
full = "A parallel computing platform and application programming interface (API) model created by Nvidia."

[cad]
disp = "CAD"
desc = "Computer-aided design"

[cname]
disp = "CNAME"
desc = "Canonical Name record"
full = "map one domain name(an alias) to another(the canonical name)"

[clos]
disp = "CLOS"
desc = "Common Lisp Object System"

[clu]
disp = "CLU"
desc = "CLUster"
full = "OOP language invented in 1975, MIT "

[cdn]
disp = "CDN"
desc = "content delivery network"

[cve]
disp = "CVE"
desc = "Common Vulnerabilities and Exposures"

[cmm]
disp = "CMM"
desc = "Capability Maturity Model"

[clhs]
disp = "clhs"
desc = "Common Lisp HyperSpec"

[cons]
disp = "cons"
desc = "CONStruct lists"

[ckeditor]
disp = "CKEditor"
desc = "An online editor formerly called FCKeditor"
full = "released in March 2003 by Frederico Caldeira Knabben, the creator of the editor"

[cas]
disp = "CAS"
desc = "Computer Algebra System"

[csg]
disp = "CSG"
desc = "Constructive Solid Geometry"

[cfd]
disp = "CFD"
desc = "computational fluid dynamics"

[cmyk]
disp = "CMYK"
desc = "Cyan, Magenta, Yellow, Dark Color Model"

[cmy]
same = "cmyk"

[cms]
disp = "CMS"
desc = "Content Management System"

[ct]
disp = "CT"
desc = "Communications Technology"
see = "IT" 

[cncf]
disp = "CNCF"
desc = "Cloud Native Computing Foundation"

[cr]
disp = "CR"
desc = "Cryptic Resolver"
full = "This is the name of this program :)"

[cc]
disp = "CC"
desc = "Creative Commons"
full = '''
Rights:
    BY: Atribution
    SA: Share Alike
    NC: Non Commercial
    ND: No Derivatives'''

[coff]
disp = "COFF"
desc = "Common Object File Format"

[clob]
disp = "CLOB"
desc = "Character Large Object"

[crt.lib]
disp = "CRT"
desc = "C Runtime Library"
see = ['UCRT']

[cqrs]
disp = "CQRS"
desc = "Command Query Responsibility Segregation pattern"

[cim]
disp = "CIM"
desc = "Common Information Model for PowerShell"

[can]
disp = "CAN"
desc = "Controller Area Network protocol"

[cpu]
disp = "CPU"
desc = "Central Processing Unit"
