[cli]
disp = "CLI"
desc = "Command-line Interface"
see = ['GUI']

[css]
disp = "CSS"
desc = "Cascading Style Sheets"

[cups]
disp = "CUPS"
desc = "Common Unix Printing System"

[cst.America]
disp = "CST(America)"
desc = "Central Standard Time(UTC-6)"
see = ['UTC']

[cst.China]
disp = "CST(China)"
desc = "China Standard Time(UTC+8)"

[crt.electronics]
disp = "CRT"
desc = "Cathode Ray Tube"

[csrf]
disp = "CSRF"
desc = "Cross Site Request Forgery"

[cur]
disp = "CUR"
desc = "Cursor image format for Windows"
see = ["ICO"]

[com]
disp = "COM"
desc = "Component Object Model"
full = "A binary-interface standard for software components introduced by Microsoft in 1993. It is used to enable inter-process communication object creation in a large range of programming languages"

[csp]
disp = "CSP"
desc = "Communicating Sequential Processs"

[cpl]
disp = "cpl"
desc = "Control PaneL"
full = "Control panel tools for Windows"

[cuda]
disp = "CUDA"
desc = "Compute Unified Device Architecture"
full = "A parallel computing platform and application programming interface (API) model created by Nvidia."

[cad]
disp = "CAD"
desc = "Computer-aided design"

[cname]
disp = "CNAME"
desc = "Canonical Name record"
full = "map one domain name(an alias) to another(the canonical name)"

[clos]
disp = "CLOS"
desc = "Common Lisp Object System"

[clu]
disp = "CLU"
desc = "CLUster"
full = "OOP language invented in 1975, MIT "

[cdn]
disp = "CDN"
desc = "Content Delivery Network"

[cve]
disp = "CVE"
desc = "Common Vulnerabilities and Exposures"

[cmm]
disp = "CMM"
desc = "Capability Maturity Model"

[clhs]
disp = "clhs"
desc = "Common Lisp HyperSpec"

[cons]
disp = "cons"
desc = "CONStruct lists"

[ckeditor]
disp = "CKEditor"
desc = "An online editor formerly called FCKeditor"
full = "released in March 2003 by Frederico Caldeira Knabben, the creator of the editor"

[cas]
disp = "CAS"
desc = "Computer Algebra System"

[csg]
disp = "CSG"
desc = "Constructive Solid Geometry"

[cfd]
disp = "CFD"
desc = "computational fluid dynamics"

[cmyk]
disp = "CMYK"
desc = "Cyan, Magenta, Yellow, Dark Color Model"

[cmy]
same = "CMYK<=>cmyk"

[cms]
disp = "CMS"
desc = "Content Management System"

[ct]
disp = "CT"
desc = "Communications Technology"
see = "IT" 

[cncf]
disp = "CNCF"
desc = "Cloud Native Computing Foundation"

[cr]
disp = "CR"
desc = "Cryptic Resolver"
full = "This is the name of this program :)"

[cc]
disp = "CC"
desc = "Creative Commons"
full = '''
Rights:
    BY: Atribution
    SA: Share Alike
    NC: Non Commercial
    ND: No Derivatives'''

[coff]
disp = "COFF"
desc = "Common Object File Format"
full = "A format for executable, object code, and shared library computer files used on Unix systems. It was introduced in Unix System V, replaced the previously used a.out format, and formed the basis for extended specifications such as XCOFF and ECOFF, before being largely replaced by ELF, introduced with SVR4"

[clob]
disp = "CLOB"
desc = "Character Large Object"

[crt.lib]
disp = "CRT"
desc = "C Runtime Library"
see = ['UCRT']

[cqrs]
disp = "CQRS"
desc = "Command Query Responsibility Segregation pattern"

[cim]
disp = "CIM"
desc = "Common Information Model for PowerShell"

[can]
disp = "CAN"
desc = "Controller Area Network protocol"

[cpu]
disp = "CPU"
desc = "Central Processing Unit"

[crc]
disp = "CRC"
desc = "Cyclic Redundancy Check"

[cdt.eclipse]
disp = "CDT"
desc = "Eclipse C/C++ Development Tooling"

[csl]
disp = "CSL"
desc = "Citation Style Language"

[cpan]
disp = "CPAN"
desc = "The Comprehensive Perl Archive Network"

[cran]
disp = "CRAN"
desc = "The Comprehensive R Archive Network"

[ctan]
disp = "CTAN"
desc = "Comprehensive TeX Archive Network"

[cde]
disp = "CDE"
desc = "Common Desktop Environment"

[cfg.grammar]
disp = "CFG"
desc = "Context-Free Grammar"
see = ['CSG']

[cfl.grammar]
disp = "CFL"
desc = "Context-Free Language, derived from a CFG"
see = ['CFG']

[csg.grammar]
disp = "CSG"
desc = "Context-Sensitive Grammar"
see = ['CFG']

[cvs]
disp = "CVS"
desc = "Concurrent Versions System"

[cisc]
disp = "CISC"
desc = "Complex Instruction Set Computing"
see = ['RISC']

[cfg.graph]
disp = "CFG"
desc = "Control Flow Graph"

[cgo]
disp = "CGO"
desc = "Code Generation and Optimization"

[cwe]
disp = "CWE"
desc = "Common Weakness Enumeration"

[ci]
disp = "CI"
desc = "Continuous Integration"

[cpd]
disp = "CPD"
desc = "Copy/Paste Detector"
full = "An add-on to PMD that uses the Rabin–Karp string search algorithm to find duplicated code. Unlike PMD, CPD works with a broader range of languages including Java,JSP, C, C++, Fortran, PHP, and C# code."
see = ['PMD']

[crx.chrome]
disp = ".crx"
desc = "Chrome extension"

[cd.command]
disp = "cd"
desc = "Change Directory"

[cd.hardware]
disp = "CD"
desc = "Compact Disc"
see = ['DVD']

[ccl]
disp = "CCL"
desc = "Clozure CL"
see = ['SBCL']

["cp/m"]
disp = "CP/M"
desc = "Control Program/Monitor and later Control Program for Microcomputers"
full = "A mass-market operating system created in 1974 for Intel 8080/85-based microcomputers by Gary Kildall of Digital Research, Inc."

[cmos]
disp = "CMOS"
desc = "Complementary Metal–Oxide–Semiconductor"

[cobol]
disp = "COBOL"
desc = "Common Business-Oriented Language"
full = "Designed in 1959 by CODASYL"

[ctss.os]
disp = "CTSS"
desc = "Compatible Time-Sharing System"

[cto]
disp = "CTO"
desc = "Chief Technology Officer"

[ctf]
disp = "CTF"
desc = "Capture the Flag Challenge"

[cors]
disp = "CORS"
desc = "Cross-Origin Resource Sharing"

[company.Emacs]
disp = "company"
desc = "Complete anything"
full = "A modular text completion framework for Emacs"

[ca]
disp = "CA"
desc = "Certificate Authority"

[cat.coreutils]
disp = "coreutils: cat"
desc = "Concatenate and write files"

[cgi]
disp = "CGI"
desc = "Common Gateway Interface"

[cjk]
disp = "CJK"
desc = "Chinese, Japanese, Korean"

[curl]
disp = "cURL"
desc = "Client URL"
