[cli]
name = "CLI"
desc = "Command-line Interface"
see = ['GUI']

[css]
name = "CSS"
desc = "Cascading Style Sheets"

[cups]
name = "CUPS"
desc = "Common Unix Printing System"

[cst.America]
name = "CST(America)"
desc = "Central Standard Time(UTC-6)"
see = ['UTC', 'EST']

[cst.China]
name = "CST(China)"
desc = "China Standard Time(UTC+8)"

[cet.Timezone]
name = "CET"
desc = "Central European Time(UTC+1)"
see = 'CEST'

[cest.Timezone]
name = "CEST"
desc = "Central European Summer Time(UTC+1)"
see = 'CET'

[crt.electronics]
name = "CRT"
desc = "Cathode Ray Tube"

[csrf]
name = "CSRF"
desc = "Cross Site Request Forgery"

[cur]
name = "CUR"
desc = "Cursor image format for Windows"
see = ["ICO"]

[csp]
name = "CSP"
desc = "Communicating Sequential Processs"

[cuda]
name = "CUDA"
desc = "Compute Unified Device Architecture"
more = "A parallel computing platform and application programming interface (API) model created by Nvidia."

[cad]
name = "CAD"
desc = "Computer-aided Design"
see = ['CAE', 'CAM']

[cae]
name = "CAE"
desc = "Computer-aided Engineering"
see = ['CAD', 'CAM']

[cam]
name = "CAM"
desc = "Computer-aided Manufacturing "
see = ['CAD', 'CAE']

[cname]
name = "CNAME"
desc = "Canonical Name record"
more = "map one domain name(an alias) to another(the canonical name)"

[clos]
name = "CLOS"
desc = "Common Lisp Object System"

[clu]
name = "CLU"
desc = "CLUster"
more = "OOP language invented in 1975, MIT "

[cdn]
name = "CDN"
desc = "Content Delivery Network"

[cve]
name = "CVE"
desc = "Common Vulnerabilities and Exposures"

[cvss]
name = "CVSS"
desc = "Common Vulnerability Scoring System"

[cmm]
name = "CMM"
desc = "Capability Maturity Model"

[clhs]
name = "clhs"
desc = "Common Lisp HyperSpec"

[cons]
name = "cons"
desc = "CONStruct lists"

[ckeditor]
name = "CKEditor"
desc = "An online editor formerly called FCKeditor"
more = "released in March 2003 by Frederico Caldeira Knabben, the creator of the editor"

[cas]
name = "CAS"
desc = "Computer Algebra System"

[csg]
name = "CSG"
desc = "Constructive Solid Geometry"

[cfd]
name = "CFD"
desc = "computational fluid dynamics"

[cmyk]
name = "CMYK"
desc = "Cyan, Magenta, Yellow, Dark Color Model"

[cmy]
name = "CMY"
same = "CMYK=>cmyk"

[cms]
name = "CMS"
desc = "Content Management System"

[ct]
name = "CT"
desc = "Communications Technology"
see = ['IT']

[cncf]
name = "CNCF"
desc = "Cloud Native Computing Foundation"

[cr]
name = "CR"
desc = "Cryptic Resolver"
more = "This is the name of this program :)"

[cr.ASCII]
name = "<CR>"
desc = "Carriage Return"
more = "ASCII code 13"
see = 'LF'

[cc]
name = "CC"
desc = "Creative Commons"
more = '''
Rights:
    BY: Atribution
    SA: Share Alike
    NC: Non Commercial
    ND: No Derivatives'''

[cc.Email]
name = "CC"
desc = "Carbon Copy (in Email)"

[coff]
name = "COFF"
desc = "Common Object File Format"
more = "A format for executable, object code, and shared library computer files used on Unix systems. It was introduced in Unix System V, replaced the previously used a.out format, and formed the basis for extended specifications such as XCOFF and ECOFF, before being largely replaced by ELF, introduced with SVR4"

[clob]
name = "CLOB"
desc = "Character Large Object"

[crt.lib]
name = "CRT"
desc = "C Runtime Library"
see = ['UCRT']

[cqrs]
name = "CQRS"
desc = "Command Query Responsibility Segregation pattern"

[can]
name = "CAN"
desc = "Controller Area Network protocol"

[cpu]
name = "CPU"
desc = "Central Processing Unit"

[crc]
name = "CRC"
desc = "Cyclic Redundancy Check"

[cdt.Eclipse]
name = "CDT"
desc = "Eclipse C/C++ Development Tooling"

[csl]
name = "CSL"
desc = "Citation Style Language"

[cpan]
name = "CPAN"
desc = "The Comprehensive Perl Archive Network"

[cran]
name = "CRAN"
desc = "The Comprehensive R Archive Network"

[ctan]
name = "CTAN"
desc = "Comprehensive TeX Archive Network"

[cde]
name = "CDE"
desc = "Common Desktop Environment"

[cfg.grammar]
name = "CFG"
desc = "Context-Free Grammar"
see = ['CSG']

[cfl.grammar]
name = "CFL"
desc = "Context-Free Language, derived from a CFG"
see = ['CFG']

[csg.grammar]
name = "CSG"
desc = "Context-Sensitive Grammar"
see = ['CFG']

[cvs]
name = "CVS"
desc = "Concurrent Versions System"

[cisc]
name = "CISC"
desc = "Complex Instruction Set Computing"
see = ['RISC']

[cfg.graph]
name = "CFG"
desc = "Control Flow Graph"

[cgo]
name = "CGO"
desc = "Code Generation and Optimization"

[cwe]
name = "CWE"
desc = "Common Weakness Enumeration"

[ci]
name = "CI"
desc = "Continuous Integration"

[cpd]
name = "CPD"
desc = "Copy/Paste Detector"
more = "An add-on to PMD that uses the Rabin–Karp string search algorithm to find duplicated code. Unlike PMD, CPD works with a broader range of languages including Java,JSP, C, C++, Fortran, PHP, and C# code."
see = ['PMD']

[crx.chrome]
name = ".crx"
desc = "Chrome extension"

[cd.command]
name = "cd"
desc = "Change Directory"

[cd.hardware]
name = "CD"
desc = "Compact Disc"
see = ['DVD']

[ccl]
name = "CCL"
desc = "Clozure CL"
see = ['SBCL']

["cp/m"]
name = "CP/M"
desc = "Control Program/Monitor and later Control Program for Microcomputers"
more = "A mass-market operating system created in 1974 for Intel 8080/85-based microcomputers by Gary Kildall of Digital Research, Inc."

[cmos]
name = "CMOS"
desc = "Complementary Metal–Oxide–Semiconductor"

[cobol]
name = "COBOL"
desc = "Common Business-Oriented Language"
more = "Designed in 1959 by CODASYL"

[ctss.os]
name = "CTSS"
desc = "Compatible Time-Sharing System"

[cto]
name = "CTO"
desc = "Chief Technology Officer"

[ctf]
name = "CTF"
desc = "Capture the Flag Challenge"

[cors]
name = "CORS"
desc = "Cross-Origin Resource Sharing"

[company.Emacs]
name = "company"
desc = "Complete anything"
more = "A modular text completion framework for Emacs"

[ca]
name = "CA"
desc = "Certificate Authority"

[cgi]
name = "CGI"
desc = "Common Gateway Interface"

[cjk]
name = "CJK"
desc = "Chinese, Japanese, Korean"

[curl]
name = "cURL"
desc = "Client URL"

[ccpc.Kernel]
name = "CCPC"
desc = "Collaborative Processor Performance Control"

[cidr]
name = "CIDR"
desc = "Classless Inter-Domain Routing"

[crud]
name = "CRUD"
desc = "Create, Read, Update and Delete"

[cui]
name = "CUI"
desc = "Character User Interface"

[cron]
name = "cron"
desc = "command run on notice"

[captcha]
name = "CAPTCHA"
desc = "Completely Automated Public Turing test to tell Computers and Humans Apart"

[cii]
name = "CII"
desc = "Core Infrastructure Initiative"

[cifs]
name = "CIFS"
desc = "Common Internet File System"
more = "Used by Windows and other operating systems to enable file sharing on a network"

[cpld]
name = "CPLD"
desc = "Complex Programmable Logic Device"

[cxl]
name = "CXL"
desc = "Compute Express Link"

[circt]
name = "CIRCT"
desc = "Circuit IR Compilers and Tools"

[cbc]
name = "AES-CBC"
desc = "Cipher Block Chaining"

[corba]
name = "CORBA"
desc = "Common Object Request Broker Architecture"

[cout]
name = "cout"
desc = "character output"
see = 'cin'

[cin]
name = "cin"
desc = "character input"
see = 'cout'

[calloc]
name = "calloc"
desc = "clear allocation"
more = "calloc will return an allocation that has already been cleared"

[cla]
name = "CLA"
desc = "Contribution License Agreement"

[cef]
name = "CEF"
desc = "Chromium Embedded Framework"

[cmmi]
name = "CMMI"
desc = "Capability Maturity Model Integration"

[cbor]
name = "CBOR"
desc = "RFC 8949 Concise Binary Object Representation"

[cen]
name = "CEN"
desc = "Comité Européen de Normalisation"
