[cups]
desc = "Common Unix Printing System"

[CST.America]
desc = "Central Standard Time(UTC-6)"
see = ['UTC']

[CST.China]
desc = "China Standard Time(UTC+8)"

[CRT]
desc = "Cathode Ray Tube"

[csrf]
desc = "Cross Site Request Forgery"

[CUR]
desc = "Cursor image format for Windows"
see = ["ICO"]

[COM]
desc = "Component Object Model"
full = "A binary-interface standard for software components introduced by Microsoft in 1993. It is used to enable inter-process communication object creation in a large range of programming languages"

[CSP]
desc = "Communicating Sequential Processs"

[cpl]
desc = "Control PaneL"
full = "Control panel tools for Windows"