[df]
disp = "df"
desc = "disk free"

[du]
disp = "du"
desc = "disk usage or directory usage (default in KB)"

[dsa]
disp = "DSA"
desc = "Digital Signature Algorithm"

[des]
disp = "DES"
desc = "Data Encryption Standard"

[dtd]
disp = "DTD"
desc = "Document Type Definition"

[dag]
disp = "DAG"
desc = "Directed Acyclic Graph"

[dns]
disp = "DNS"
desc = "Domain Name System"

[dft]
disp = "DFT"
desc = "Discrete Fourier Transform"

[darpa]
disp = "DARPA"
desc = "The Defense Advanced Research Projects Agency"

[dmi]
disp = "DMI"
desc = "Desktop Management Interface"
full = "It's an industry framework for managing and keeping track of hardware and software components in a system of personal computers from a central location."

[dbus]
disp = "DBUS"
desc = "Desktop Bus"

[d-bus]
same = 'D-BUS<=>dbus'

[drm]
disp = "DRM"
desc = "Direct Rendering Manager"

[doi]
disp = "DOI"
desc = "Digital Object Unique Identifier"

[dxf]
disp = "DXF"
desc = "AutoCAD Drawing Interchange Format"

[dwg]
disp = "dwg"
desc = "from drawing"
full = "a proprietary binary file format used for storing two- and three- dimensional design data and metadata"

[ddd]
disp = "DDD"
desc = "Domain Driven Design"

[dao]
disp = "DAO"
desc = "Data Access Object"

[dfm]
disp = "DFM"
desc = "Delphi Form files"

[ddl]
disp = "DDL"
desc = "Data Definition Language"

[dap]
disp = "DAP"
desc = "Debug Adapter Protocol"

[dia]
disp = "DIA SDK"
desc = "Microsoft Debug Interface Access Software Development Kit"
full = "Using DIA API, you can develop applications that search for and browse debug information stored in a .pdb file. Such applications could, for example, report stack trace-back information and analyze performance data."
see = ["pdb"]

[dism]
disc = "DISM"
desc = "Deployment Image Servicing and Management by Windows"

[def.file]
disp = ".def"
desc = "module-definition file"
full = "reference: https://docs.microsoft.com/en-us/cpp/build/exporting-from-a-dll-using-def-files?view=msvc-170"

[dll]
disp = "DLL"
desc = "Dynamic Link Library"

[dma]
disp = "DMA"
desc = "Direct Memory Access"

[dsp]
disp = "DSP"
desc = "Digital Signal Processing"

[dac]
disp = "DAC"
desc = "Digital to Analog Converter"
see = ["ADC"]

[dmd]
disp = "DMD"
desc = "Digital Mars D Compiler"

[dwarf]
disp = "DWARF"
desc = "The name is a medieval fantasy complement to 'ELF' that had no official meaning"
full = "A widely used, standardized debugging data format, generated by the Gnu C/C++ Compiler. An equivalent 'PDB' file is generated by the Microsoft Visual C++ Compiler."
see = ['ELF', 'PDB']

[dpi]
disp = "DPI"
desc = "Dots per inch"

[dfa]
disp = "DFA"
desc = "Deterministic Finite Automata"

[dmca]
disp = "DMCA"
desc = "Digital Millennium Copyright Act"

[dips.dlang]
disp = "DIPs"
desc = "D Improvement Proposals"

[dvd]
disp = "DVD"
desc = "Digital Video Disc"
see = ['CD']

[dsl.hardware]
disp = "DSL"
desc = "Digital Subscriber Line"
see = ['ADSL']

[dsl.lang]
disp = "DSL"
desc = "Domain Specific Language"

[dom]
disp = "DOM"
desc = "Document Object Model"

[dos]
disp = "DOS"
desc = "Disk Operating System"
full = "later became a common shorthand for disk-based operating systems on IBM PC compatibles"

[ddos]
disp = "DDoS"
desc = "Distributed Denial-of-Service"

[dhh]
disp = "DHH"
desc = "David Heinemeier Hansson"
