[df]
disp = "df"
desc = "disk free"

[du]
disp = "du"
desc = "disk usage or directory usage (default in KB)"

[dsa]
disp = "DSA"
desc = "Digital Signature Algorithm"

[des]
disp = "DES"
desc = "Data Encryption Standard"

[dtd]
disp = "DTD"
desc = "Document Type Definition"

[dag]
disp = "DAG"
desc = "Directed Acyclic Graph"

[dns]
disp = "DNS"
desc = "Domain Name System"

[dft]
disp = "DFT"
desc = "Discrete Fourier Transform"

[darpa]
disp = "DARPA"
desc = "The Defense Advanced Research Projects Agency"

[dmi]
disp = "DMI"
desc = "Desktop Management Interface"
full = "It's an industry framework for managing and keeping track of hardware and software components in a system of personal computers from a central location."

[dbus]
disp = "DBUS"
desc = "Desktop Bus"

[d-bus]
same = 'dbus'

[drm]
disp = "DRM"
desc = "Direct Rendering Manager"

[doi]
disp = "DOI"
desc = "Digital Object Unique Identifier"

[dxf]
disp = "DXF"
desc = "AutoCAD Drawing Interchange Format"

[dwg]
disp = "dwg"
desc = "from drawing"
full = "a proprietary binary file format used for storing two- and three- dimensional design data and metadata"

[ddd]
disp = "DDD"
desc = "Domain Driven Design"

[dao]
disp = "DAO"
desc = "Data Access Object"

[dfm]
disp = "DFM"
desc = "Delphi Form files"

[ddl]
disp = "DDL"
desc = "Data Definition Language"

