[df]
desc = "disk free"

[du]
desc = "disk usage or directory usage (default in KB)"

[DSA]
desc = "Digital Signature Algorithm"

[DES]
desc = "Data Encryption Standard"

[DTD]
desc = "Document Type Definition"

[DAG]
desc = "Directed Acyclic Graph"

[DNS]
desc = "Domain Name System"

[DFT]
desc = "Discrete Fourier Transform"

[DARPA]
desc = "The Defense Advanced Research Projects Agency"

[DMI]
desc = "Desktop Management Interface"
full = "It's an industry framework for managing and keeping track of hardware and software components in a system of personal computers from a central location."

[DBUS]
desc = "Desktop Bus"

[D-BUS]
same = 'DBUS'

[DRM]
desc = "Direct Rendering Manager"

[DOI]
desc = "Digital Object Unique Identifier"
