[df]
name = "df"
desc = "disk free"

[du]
name = "du"
desc = "disk usage or directory usage (default in KB)"

[dsa]
name = "DSA"
desc = "Digital Signature Algorithm"

[des]
name = "DES"
desc = "Data Encryption Standard"

[dtd]
name = "DTD"
desc = "Document Type Definition"

[dag]
name = "DAG"
desc = "Directed Acyclic Graph"

[dns]
name = "DNS"
desc = "Domain Name System"

[ddns]
name = "DDNS"
desc = "Dynamic DNS"

[dot.DNS]
name = "DoT"
desc = "DNS over TLS"

[doh.DNS]
name = "DoH"
desc = "DNS over HTTPS"

[dft]
name = "DFT"
desc = "Discrete Fourier Transform"

[darpa]
name = "DARPA"
desc = "The Defense Advanced Research Projects Agency"

[dmi]
name = "DMI"
desc = "Desktop Management Interface"
more = "It's an industry framework for managing and keeping track of hardware and software components in a system of personal computers from a central location."

[dbus]
name = "DBUS"
desc = "Desktop Bus"

[d-bus]
name = "D-BUS"
same = 'DBUS=>dbus'

[drm.Render]
name = "DRM"
desc = "Direct Rendering Manager"

[doi]
name = "DOI"
desc = "Digital Object Unique Identifier"

[dxf]
name = "DXF"
desc = "AutoCAD Drawing Exchange Format"
more = "A CAD data file format developed by Autodesk for enabling data interoperability between AutoCAD and other programs."

[dwg]
name = "dwg"
desc = "from drawing"
more = "a proprietary binary file format used for storing two- and three- dimensional design data and metadata"

[ddd]
name = "DDD"
desc = "Domain Driven Design"

[dao]
name = "DAO"
desc = "Data Access Object"
more = "It provides an abstract interface to some type of database or other persistence mechanism. By mapping application calls to the persistence layer, the DAO provides data operations without exposing database details"
see = 'DTO'

[dto]
name = "DTO"
desc = "Data Transfer Object"
more = "An object that carries data between processes. The motivation for its use is that communication between processes is usually done resorting to remote interfaces (e.g., web services), where each call is an expensive operation"
see = 'DAO'

[dfm]
name = "DFM"
desc = "Delphi Form files"

[ddl]
name = "DDL"
desc = "Data Definition Language"

[dap]
name = "DAP"
desc = "Debug Adapter Protocol"

[dism]
disc = "DISM"
desc = "Deployment Image Servicing and Management by Windows"

[def.file]
name = ".def"
desc = "module-definition file"
more = "Reference: https://docs.microsoft.com/en-us/cpp/build/exporting-from-a-dll-using-def-files?view=msvc-170"

[dma]
name = "DMA"
desc = "Direct Memory Access"

[dsp]
name = "DSP"
desc = "Digital Signal Processing"

[dac]
name = "DAC"
desc = "Digital to Analog Converter"
see = ["ADC"]

[dmd]
name = "DMD"
desc = "Digital Mars D Compiler"
see = ['LDC', 'DMD']

[dcd]
name = "DCD"
desc = "D Completion Daemon"
more = "An auto-complete program for the D programming language"

[dwarf]
name = "DWARF"
desc = "The name is a medieval fantasy complement to 'ELF' that had no official meaning"
more = "A widely used, standardized debugging data format, generated by the Gnu C/C++ Compiler. An equivalent 'PDB' file is generated by the Microsoft Visual C++ Compiler."
see = ['ELF', 'PDB']

[dpi]
name = "DPI"
desc = "Dots per inch"
see = 'PPI'

[dfa]
name = "DFA"
desc = "Deterministic Finite Automata"

[dmca]
name = "DMCA"
desc = "Digital Millennium Copyright Act"

[dips.dlang]
name = "DIPs"
desc = "D Improvement Proposals"

[dvd]
name = "DVD"
desc = "Digital Video Disc"
see = ['CD']

[dsl.hardware]
name = "DSL"
desc = "Digital Subscriber Line"
see = ['ADSL']

[dsl.lang]
name = "DSL"
desc = "Domain Specific Language"

[dom]
name = "DOM"
desc = "Document Object Model"

[ddos]
name = "DDoS"
desc = "Distributed Denial-of-Service"

[dhh]
name = "DHH"
desc = "David Heinemeier Hansson"

[dpu]
name = "DPU"
desc = "Data Processing Unit"

[dec]
name = "DEC"
desc = "Digital Equipment Corporation"

[dtrace]
name = "dtrace"
desc = "dynamic tracing framework"

[dwim]
name = "dwim"
desc = "do what I mean"

[dc.current]
name = "DC"
desc = "Direct Current"
see = 'AC'

[dc]
name = "dc"
desc = "Desktop Calculator"
more = "Arbitrary precision RPN calculator"

[dbx]
name = "DBX"
desc = "debugger for *nix"

[db]
name = "DB"
desc = "Database"

[dbms]
name = "DBMS"
desc = "Database Management System"

[dry]
name = "DRY"
desc = "Don't repeat yourself"

[dhcp]
name = "DHCP"
desc = "Dynamic Host Configuration Protocol"

[dnf.RPM]
name = "DNF"
desc = "Dandified YUM"
more = "The next-generation version of the Yellowdog Updater, Modified (yum), a package manager for .rpm-based distributions. DNF was introduced in Fedora 18 in 2013, it has been the default package manager since Fedora 22 in 2015 and Red Hat Enterprise Linux 8"

[dbm]
name = "dbm"
desc = "Database Manager"
more = "A library and file format providing fast, single-keyed access to data. A key-value database from the original Unix, dbm is an early example of a NoSQL system."

[dsa.Debian]
name = "DSA"
desc = "Debian Security Advisories"

[drm.Right]
name = "DRM"
desc = "Digital Rights Management"

[dvi.TeX]
name = ".dvi"
desc = "DeVice-Independent file"
more = """Meaning that the file may be processed for printing or viewing on most kinds of typographic output device or display.

  A DVI file (a file with the type or extension dvi) is the main output file of "original" TeX (later TeX-like systems, such as pdfTeX may use other formats).

  Any TeX input file should produce the same DVI file regardless of which implementation of TeX is used to produce it
"""

[dbaas]
name = "DBaaS"
desc = "DataBase as a Service"

[dsdm]
name = "DSDM"
desc = "Dynamic Systems Development Method"

[dvi]
name = "DVI"
desc = "Digital Visual Interface"

[doors]
name = "DOORS"
desc = "Rational Dynamic Object Oriented Requirements System"

[dplyr]
name = "R package dplyr"
desc = "data.frame 'apply' functions in R"
more = "See https://github.com/tidyverse/dplyr/issues/1857"

[dram]
name = "DRAM"
desc = "Dynamic Random-Access Memory"
see = 'SRAM'

[drc]
name = "DRC"
desc = "Design Rule Checking"
see = 'ERC'

[dst]
name = "DST"
desc = "Daylight Saving Time"

[dri]
name = "DRI"
desc = "Direct Rendering Infrastructure"
more = "A framework for allowing direct access to graphics hardware under the X Window System in a safe and efficient manner. It includes changes to the X server, to several client libraries, and to the kernel (DRM, Direct Rendering Manager). The most important use for the DRI is to create fast OpenGL implementations providing hardware acceleration for Mesa. Several 3D accelerated drivers have been written to the DRI specification, including drivers for chipsets produced by 3DFX, AMD (formerly ATI), Intel and Matrox."

[dip]
name = "DIP"
desc = "Dependency Inversion Principle"

[deque]
name = "deque"
desc = "double-ended queue"
more = "An abstract data type that generalizes a queue, for which elements can be added to or removed from either the front (head) or back (tail)"

[dbc]
name = "DBC"
desc = "Design By Contrast"

[d-pointer]
name = "d-pointer"
desc = "data pointer"
more = "It's an opaque pointer always used to point to data member in C++"

[ddj]
name = "DDJ"
desc = "Dr. Dobb's Journal"
more = "Visit: https://www.drdobbs.com/"

[dl.HTML]
name = "<dl>"
desc = "Description List"
see = ['dt', 'dd']

[dt.HTML]
name = "<dt>"
desc = "Description Element"
see = ['dl', 'dd']

[dd.HTML]
name = "<dd>"
desc = "Description element Description"
see = ['dl', 'dt']

[dnd]
name = "DND"
desc = "Drag-and-Drop"

[dall-e]
name = "DALL-E"
desc = "WALL-E and Salvador Dalí"
more = "The Spanish surrealist artist Salvador Dalí"
