[df]
desc = "disk free"

[du]
desc = "disk usage or directory usage (default in KB)"

[DSA]
desc = "Digital Signature Algorithm"

[DES]
desc = "Data Encryption Standard"

[DTD]
desc = "Document Type Definition"