[elf]
disp = "ELF"
desc = "Executable and Linkable Format"

[emacs]
disp = "Emacs"
desc = "Edit macros"
full = "a feature-rich editor"
see = ["Vim"]

[exif]
disp = "Exif"
desc = "Exchangeable image file format"
full = "Released in 1995, revised in 2019"

[edn]
disp = "edn"
desc = "Extensible Data Notation"

[eabi]
disp = "EABI"
desc = "Embedded Applications Binary Interface"

[etl]
disp = "ETL"
desc = "Extract, Transform, Load"

[eopl]
disp = "EOPL"
desc = "Essentials of Programming Languages Language"

[elt]
disp = "elt"
desc = "element"
full = "a function in Common Lisp"

[evdev]
disp = "evdev"
desc = "Xorg input driver for LinuxÂ´s generic EVent devices"

[erp]
disp = "ERP"
desc = "Enterprise Resource Planning"

[eda]
disp = "EDA"
desc = "Electronic Design Automation"

[eta]
disp = "ETA"
desc = "Estimated Time of Arrival"
