[elf]
name = "ELF"
desc = "Executable and Linkable Format"
more = "First published in the specification for the application binary interface (ABI) of the Unix operating system version named System V Release 4 (SVR4)"

[emacs]
name = "Emacs"
desc = "Edit macros"
more = "A feature-rich editor"
see = ["Vim"]

[ee]
name = "ee"
desc = "easy editor"
more = "Text editor in FreeBSD"

[exif]
name = "Exif"
desc = "Exchangeable image file format"
more = "Released in 1995, revised in 2019"

[edn]
name = "edn"
desc = "Extensible Data Notation"

[eabi]
name = "EABI"
desc = "Embedded Applications Binary Interface"

[etl]
name = "ETL"
desc = "Extract, Transform, Load"

[eopl]
name = "EOPL"
desc = "Essentials of Programming Languages Language"

[elt]
name = "elt"
desc = "element"
more = "a function in Common Lisp"

[evdev]
name = "evdev"
desc = "Xorg input driver for LinuxÂ´s generic EVent devices"

[erp]
name = "ERP"
desc = "Enterprise Resource Planning"

[eda]
name = "EDA"
desc = "Electronic Design Automation"

[eta]
name = "ETA"
desc = "Estimated Time of Arrival"

[etr]
name = "ETR"
desc = "Elapsed Time Reminder"

[ecma]
name = "ECMA"
desc = "European Computer Manufacturers Association"

[ebcdic]
name = "EBCDIC"
desc = "Extended Binary Coded Decimal Interchange Code"
more = "an 8-bit character encoding used mainly on IBM mainframe and IBM midrange computer operating systems"

[ets]
name = "ETS"
desc = "Erlang Built-in Term Storage"

[esp.assembly]
name = "ESP"
desc = "Current Stack Pointer"

[ebp.assembly]
name = "EBP"
desc = "Base Pointer for the current stack frame"

[eip.assembly]
name = "EIP"
desc = "Instruction Pointer"

[eca.Eclipse]
name = "ECA"
desc = "Eclipse Contributor Agreement"

[elk]
name = "ELK"
desc = "Elasticsearch, Logstash, and Kibana"

[erd]
name = "ERD"
desc = "Entity Relationship Diagram"

[eprom]
name = "EPROM"
desc = "Erasable Programmable Read-only Memory"
see = ['PROM']

[eeprom]
name = "EEPROM"
desc = "Electrically Erasable Programmable Read-only Memory"
more = "A type of non-volatile memory used in computers, integrated in microcontrollers for smart cards and remote keyless systems, and other electronic devices to store relatively small amounts of data"
see = ['EPROM']

[elisp]
name = "ELisp"
desc = "Emacs Lisp"
see = ['Emacs', 'SBCL', 'CCL']

[el]
same = ".el file=>elisp"

[elc]
name = ".elc"
desc = "ELisp byte-compiled code file"
see = ['Elisp']

[erts]
name = "ERTS"
desc = "Erlang Run-Time System"

[erlang]
name = "Erlang"
desc = "Ericsson Language"

[elpa]
name = "GNU elpa"
desc = "GNU Emacs Lisp Package Archive"
see = ['MELPA']

[ed]
name = "ed"
desc = "The GNU line editor"

[ecdsa]
name = "ECDSA"
desc = "Elliptic Curve Digital Signature Algorithm"

[epoll]
name = "epoll"
desc = "event poll"
more = "A Linux kernel system call for a scalable I/O event notification mechanism, first introduced in version 2.5.44 of the Linux kernel. Its function is to monitor multiple file descriptors to see whether I/O is possible on any of them. It is meant to replace the older POSIX select(2)and poll(2) system calls, to achieve better performance in more demanding applications, where the number of watched file descriptors is large (unlike the older system calls, which operate in O(n) time, epoll operates in O(1) time)"
see = ['kqueue', 'IOCP']

[es]
name = "ES"
desc = "ECMAScript"

[eww.Emacs]
name = "eww"
desc = "Emacs Web Wowser"
more = "A web browser written entirely in Emacs Lisp. It became part of GNU Emacs starting with version 24.4"

[epub]
name = "EPUB"
desc = "Electronic Publication"
more = "An e-book file format. It became an official standard of the IDPF in September 2007, superseding the older Open eBook standard"

[eof]
name = "EOF"
desc = "End-of-file"
more = "When you Ctrl-d"

[eol]
name = "EOL"
desc = "End-of-Life"

[ede.Emacs]
name = "EDE"
desc = "Emacs Development Environment"

[elsa.Emacs]
name = "elsa"
desc = "Emacs Lisp Static Analyser"

[epel]
name = "EPEL"
desc = "Extra Packages for Enterprise Linux"
more = "A Fedora Special Interest Group that creates, maintains, and manages a high quality set of additional packages for Enterprise Linux, including, but not limited to, Red Hat Enterprise Linux (RHEL), CentOS, Scientific Linux (SL), Oracle Linux (OL), AlmaLinux (AL) and Rocky Linux (RL)."

[ere]
name = "ERE"
desc = "Extended Regular Expressions"

[eddsa]
name = "EdDSA"
desc = "Edwards-curve Digital Signature Algorithm"

[ewf]
name = "EWF"
desc = "Eiffel Web framework"

[ei]
name = "EI"
desc = "Engineering Index"
see = ['SCI']

[ecc]
name = "ECC"
desc = "Elliptic-curve Cryptography"

[eniac]
name = "ENIAC"
desc = "Electronic Numerical Integrator and Computer"
more = "The first programmable, electronic, general-purpose digital computer, completed in 1945"

[edvac]
name = "EDVAC"
desc = "Electronic Discrete Variable Automatic Computer"
more = "ENIAC inventors, John Mauchly and J. Presper Eckert, proposed the EDVAC's construction in August 1944. A contract to build the new computer was signed in April 1946 with an initial budget of US$100,000. EDVAC was delivered to the Ballistic Research Laboratory in 1949."

[edsac]
name = "EDSAC"
desc = "Electronic Delay Storage Automatic Calculator"
more = "An early British computer, inspired by John von Neumann's seminal First Draft of a Report on the EDVAC. Released in May 1949"
see = 'EDVAC'

[erc]
name = "ERC"
desc = "Electrical Rule Check"
see = 'DRC'

[ecad]
name = "ECAD"
desc = "Electronic Computer-Aided Design"
see = 'MCAD'

[emmc]
name = "eMMC"
desc = "Embedded MultiMedia Card"

[est.Timezone]
name = "EST(America)"
desc = "Eastern Standard Time(UTC-5)"
see = 'CST'

[ega]
name = "EGA"
desc = "Enhanced Graphics Adapter"

[efi]
name = "EFI"
desc = "Extensible Firmware Interface"
see = 'ESP'

[esp]
name = "ESP"
desc = "Extensible Firmware Interface system partition"
more = """ESP is a partition on a data storage device (usually a hard disk drive or solid-state drive) that is used by computers having the Unified Extensible Firmware Interface (UEFI). When a computer is booted, UEFI firmware loads files stored on the ESP to start installed operating systems and various utilities.

  An ESP contains the boot loaders or kernel images for all installed operating systems (which are contained in other partitions), device driver files for hardware devices present in a computer and used by the firmware at boot time, system utility programs that are intended to be run before an operating system is booted, and data files such as error logs."""

[em]
name = "em in CSS"
desc = "'M'"
more = "In modern usage it simply refers to the size of the font"

[euc]
name = "EUC"
desc = "Extended Unix Code"
more = """A multibyte character encoding system used primarily for Japanese, Korean, and simplified Chinese.

  Note: Modern applications are more likely to use *UTF-8*, which supports all of the glyphs of the EUC codes, and more, and is generally more portable with fewer vendor deviations and errors."""

[etag]
name = "ETag"
desc = "HTTP entity tag"
more = "It's part of HTTP, the protocol for the World Wide Web. It is one of several mechanisms that HTTP provides for Web cache validation, which allows a client to make conditional requests. This mechanism allows caches to be more efficient and saves bandwidth, as a Web server does not need to send a full response if the content has not changed. ETags can also be used for optimistic concurrency control to help prevent simultaneous updates of a resource from overwriting each other"

[eula]
name = "EULA"
desc = "End-User License Agreement"

[eoi]
name = "EOI"
desc = "End Of Interrupt"

[ecos]
name = "eCos"
desc = "Embedded Configurable Operating System"
more = "A free and open-source RTOS intended for embedded systems and applications which need only one process with multiple threads. initially developed in 1997 by Cygnus Solutions which was later bought by Red Hat. In early 2002, Red Hat ceased development of eCos and laid off the staff of the project. Many of the laid-off staff continued to work on eCos and some formed their own companies providing services for the software. In January 2004, at the request of the eCos developers, Red Hat agreed to transfer the eCos copyrights to the Free Software Foundation in October 2005, a process finally completed in May 2008."

[ebpf]
name = "eBPF"
desc = "extended Berkeley Packet Filter"

[ens33]
name = "ens33"
desc = "Ethernet Network Server 33"
more = "A physical network interface card (NIC) or a virtual one created by software like a virtual machine"
