[ELF]
desc = "Executable and Linkable Format"

[Emacs]
desc = "Edit macros"
full = "a feature-rich editor"
see = ["Vim"]

[Exif]
desc = "Exchangeable image file format"
full = "Released in 1995, revised in 2019"

[edn]
desc = "Extensible Data Notation"

[EABI]
desc = "Embedded Applications Binary Interface"

[ETL]
desc = "Extract, Transform, Load"