[fwupd]
disp = "fwupd"
desc = "Firmware Update daemon on Linux-based system"

[frum]
disp = "frum"
desc = "Fast RUby Manager"

[fosdem]
disp = "FOSDEM"
desc = "Free and Open Source Developers European Meeting"

[fm]
disp = "FM"
desc = "Frequency Modulation"

[fft]
disp = "FFT"
desc = "Fast Fourier Transform"

[ffmpeg]
disp = "FFmpeg"
desc = "Fast Forward MPEG"
see = ['MPEG']

[fsf]
disp = "FSF"
desc = "Free Software Foundation"

[flops]
disp = "FLO/s"
desc = "Floating Point Operations Per Second"

[fcitx]
disp = "Fcitx"
desc = "pronounce as [Faitiks]"
full = "An input method framework with extension support for the X Window System. It supports typing with many languages all over the world with a large number of engines."
see = ['IBus']

[flex]
disp = "Flex"
desc = "Flex lexical analyser"
see = ['Yacc']

[fpga]
disp = "FPGA"
desc = "Field-programmable Gate Array"

[foss]
disp = "FOSS"
desc = "Free and Open-Source Software"

[ffi]
disp = "FFI"
desc = "Foreign Function Interface"

[ftp]
disp = "FTP"
desc = "File Transfer Protocol"

[fuse]
disp = "FUSE"
desc = "Filesystem in Userspace"
full = "A software interface for Unix and Unix-like computer operating systems that lets non-privileged users create their own file systems without editing kernel code. This is achieved by running file system code in user space while the FUSE module provides only a bridge to the actual kernel interfaces."
