[gdm]
disp = "GDM"
desc = "GNOME Display Manager"
full = "The GNOME Display Manager (GDM) is a program that manages graphical display servers and handles graphical user logins. "

[gif]
disp = "GIF"
desc = "Graphics Interchange Format"
full = "Released in 1987. GIF images are compressed using LZW lossless data compression algorithm. By 2004 all the relevant patents of LZW had expired."

[gm]
disp = "GM"
desc = "General Motors"

[gpgpu]
disp = "GPGPU"
desc = "General-Purpose computing on the GPU"

[glsl]
disp = "GLSL"
desc = "OpenGL Shading Language"

[gps]
disp = "GPS"
desc = "Global Positioning System"

[gdi]
disp = "GDI"
desc = "Graphics Device Interface by Microsoft Windows"

[gsl]
disp = "GSL"
desc = "GNU Scientific Library"

[gvdb]
disp = "GVDB"
desc = "GVariant Database"

[gdk]
disp = "GDK"
desc = "GIMP Drawing Kit"

[gtk]
disp = "GTK"
desc = "GIMP ToolKit, formerly GTK+"
full = "It is a free and open-source cross-platform widget toolkit for creating graphical user interfaces"

[gobject]
disp = "GObject"
desc = "GLib object system"

[gda]
disp = "GDA"
desc = "GNU Data Access"

[gom]
disp = "GOM"
desc = "GNOME object mapper"

[gap]
disp = "GAP"
desc = "Groups, Algorithms and Programming"
full = "is a computer algebra system for computational discrete algebra with particular emphasis on computational group theory."

[ginac]
disp = "GiNaC"
desc = "ginac is not a CAS"
full = "C++ library for symbolic computing"

[gimp]
disp = "GIMP"
desc = "GNU Image Manipulation Program"

[gegl]
disp = "GEGL"
desc = "Generic Graphics Library, mainly for GIMP"

[gtd]
disp = "GTD"
desc = "Getting Things Done"

[glm]
disp = "GLM"
desc = "OpenGL Mathematics"

[gsoc]
disp = "GSoC"
desc = "Google Summer of Code"

[gcc]
disp = "GCC"
desc = "GNU Compiler Collection"

[gmp]
disp = "GMP"
desc = "GNU Multiple Precision Arithmetic Library"

[gomp]
disp = "GNU OpenMP"
desc = "OpenMP implementation for GCC"
see = ['OpenMP']

[gpio]
disp = "GPIO"
desc = "General-purpose Input/output"

[glr]
disp = "GLR"
desc = "Generalized LR"

[gdb]
disp = "GDB"
desc = "GNU Debugger"
