[HEVC]
desc = "High Efficiency Video Coding"
full = "Known as H.265 completed in 2013"

["H.264"]
desc = "A video compression standard"
see = ['AVC']

["H.265"]
desc = "A video compression standard"
see = ['HEVC']

[HMI]
desc = "Human-Machine Interface"