[hevc]
name = "HEVC"
desc = "High Efficiency Video Coding"
more = "Known as H.265 completed in 2013"

["h.264"]
name = "H.264"
desc = "A video compression standard"
see = ['AVC']

["h.265"]
name = "H.265"
desc = "A video compression standard"
see = ['HEVC']

[hmi]
name = "HMI"
desc = "Human-Machine Interface"

[hdfs]
name = "HDFS"
desc = "Hadoop Distributed File System"

[hsl]
name = "HSL"
desc = "Hue, Saturation, Value"

[hof]
name = "HOF"
desc = "Higher-order functions"

[hci]
name = "HCI"
desc = "Human Computer Interface"

[hla]
name = "HLA"
desc = "High Level Assembly Language"

[hls.color]
name = "HLS"
desc = "Hue, Lightness, Saturation Color Model"

[hls.hardware]
name = "HLS"
desc = "High Level Synthesis"

[hcl]
name = "HCL"
desc = "Hue, Chroma, Luminance Color Space Model"

[hms]
name = "HMS"
desc = "Huawei Mobile Services"

[hdr]
name = "HDR"
desc = "High Dynamic Range"

[htap]
name = "HTAP"
desc = "Hybrid Transactional/Analytical Processing"

[hvm]
name = "HVM"
desc = "Hardware VM"

[hlsl]
name = "HLSL"
desc = "High-Level Shading Language"

[hpc]
name = "HPC"
desc = "High Performance Computing"

[haml]
name = "HAML"
desc = "HTML abstraction markup language"

[hdl]
name = "HDL"
desc = "Hardware Description Language"

[hidpi]
name = "HiDPI"
desc = "High Dots Per Inch"

[hts]
name = "HTS"
desc = "High Throughput Sequencing data"

[http]
name = "HTTP"
desc = "Hypertext Transfer Protocol"

[hls.HTTP]
name = "HLS"
desc = "HTTP Live Streaming"

[https]
name = "HTTPS"
desc = "Hypertext Transfer Protocol Over Secure Socket Layer"

[hda]
name = "/dev/hda"
desc = "The master disk on IDE primary controller"
more = "hdb, hdc and so on"
see = ['IDE', 'sda']

[hdb]
same = 'hda'

[html]
name = "HTML"
desc = "HyperText Markup Language"

[hp]
name = "HP"
desc = "Hewlett-Packard Company"

[hhvm]
name = "HHVM"
desc = "HipHop Virtual Machine"

[hpc.counter]
name = "HPC"
desc = "Hardware Performance Counters"
more = "A set of special-purpose registers built into modern microprocessors to store the counts of hardware-related activities within computer systems"

[hld]
name = "HLD"
desc = "High-level design"

[hal]
name = "HAL"
desc = "Hardware Abstraction Layer"

[hig]
name = "HIG"
desc = "Human Interface Guidelines"

[hbm]
name = "HBM"
desc = "High Bandwidth Memory"

[hgfs]
name = "HGFS"
desc = "VMware Host Guest File System"

[hkp]
name = "HKP"
desc = "OpenPGP HTTP Keyserver Protocol"

[hcl.HashiCorp]
name = "HCL"
desc = "HashiCorp Configuration Language"

[hdlc]
name = "HDLC"
desc = "High-Level Data Link Control"

[hol]
name = "HOL"
decs = "proof assistant for Higher-Order Logic"

[hdmi]
name = "HDMI"
desc = "High-Definition Multimedia Interface"

[hid]
name = "HID"
desc = "Human Interface Device"
more = "A type of computer device usually used by humans that takes input from humans and gives output to humans."

[haxm]
name = "HAXM"
desc = "Intel Hardware Accelerated Execution Manager"
more = """A cross-platform hardware-assisted virtualization engine (hypervisor), widely used as an accelerator for Android Emulator and QEMU. It has always supported running on Windows and macOS, and has been ported to other host operating systems as well, such as Linux and NetBSD.

HAXM runs as a kernel-mode driver on the host operating system, and provides a KVM-like interface to user space, thereby enabling applications like QEMU to utilize the hardware virtualization capabilities built into modern Intel CPUs, namely Intel Virtualization Technology."""

[hurd]
name = "GNU Hurd"
desc = "Hird of Unix-Replacing Daemons"
more = "As both hurd and hird are homophones of the English word herd, the full name GNU Hurd is also a play on the words herd of gnus, reflecting how the kernel works."

[htaccess]
name = ".htaccess"
desc = "hypertext access"
more = "A directory-level configuration file supported by several web servers, used for configuration of website-access issues, such as URL redirection, URL shortening, access control (for different web pages and files)"
