[hevc]
disp = "HEVC"
desc = "High Efficiency Video Coding"
full = "Known as H.265 completed in 2013"

["h.264"]
disp = "H.264"
desc = "A video compression standard"
see = ['AVC']

["h.265"]
disp = "H.265"
desc = "A video compression standard"
see = ['HEVC']

[hmi]
disp = "HMI"
desc = "Human-Machine Interface"

[hdfs]
disp = "HDFS"
desc = "Hadoop Distributed File System"

[hsl]
disp = "HSL"
desc = "Hue, Saturation, Value"

[hof]
disp = "HOF"
desc = "Higher-order functions"

[hci]
disp = "HCI"
desc = "Human Computer Interface"

[hla]
disp = "HLA"
desc = "High Level Assembly Language"

[hls]
disp = "HLS"
desc = "Hue, Lightness, Saturation Color Model"

[hcl]
disp = "HCL"
desc = "Hue, Chroma, Luminance Color Space Model"

[hms]
disp = "HMS"
desc = "Huawei Mobile Services"

[hdr]
disp = "HDR"
desc = "High Dynamic Range"
