[HEVC]
desc = "High Efficiency Video Coding"
full = "Known as H.265 completed in 2013"

["H.264"]
desc = "A video compression standard"
see = ['AVC']

["H.265"]
desc = "A video compression standard"
see = ['HEVC']

[HMI]
desc = "Human-Machine Interface"

[HDFS]
desc = "Hadoop Distributed File System"

[hsl]
desc = "Hue, Saturation, Value"

[HOF]
desc = "Higher-order functions"

[HCI]
desc = "Human Computer Interface"

[HLA]
desc = "High Level Assembly Language"

[HLS]
desc = "Hue, Lightness, Saturation Color Model"

[HCL]
desc = "Hue, Chroma, Luminance Color Space Model"