[ietf]
disp = "IETF"
desc = "Internet Engineering Task Force"

[ico]
disp = "ICO"
desc = "Icon image format for Windows"
see = ["CUR"]

[isv]
disp = "ISV"
desc = "Independent Software Vendor"

[ieee]
disp = "IEEE"
desc = "Institute of Electrical and Electronics Engineers"

[inria]
disp = "INRIA"
desc = "French Institute for Research in Computer Science and Automation"

[isbn]
disp = "ISBN"
desc = "International Standard Book Number"
see = ['ISSN']

[issn]
disp = "ISSN"
desc = "International Standard Serial Number"
see = ['ISBN']

[ike]
disp = "IKE"
desc = "Internet Key Exchange"

[icann]
disp = "ICANN"
desc = "The Internet Corporation for Assigned Names and Numbers"

[idc]
disp = "IDC"
desc = "Internet Data Center"

[it]
disp = "IT"
desc = "Information Technology"
see = "CT" 


[ict]
disp = "ICT"
desc = "Information and Communications Technology"
see = ["IT","CT"]

[iana]
disp = "IANA"
desc = "Internet Assigned Numbers Authority"

[iso]
disp = "ISO"
desc = "International Organization for Standardization"

[iec]
disp = "IEC"
desc = "International Electrotechnical Commission"
