[IETF]
desc = "Internet Engineering Task Force"

[ICO]
desc = "Icon image format for Windows"
see = ["CUR"]

[ISV]
desc = "Independent Software Vendor"

[IC.star]
desc = "Index Catalogues"
see = ['NGC']

[IEEE]
desc = "Institute of Electrical and Electronics Engineers"

[INRIA]
desc = "French Institute for Research in Computer Science and Automation"