[ietf]
name = "IETF"
desc = "Internet Engineering Task Force"

[ico]
name = "ICO"
desc = "Icon image format for Windows"
see = ["CUR"]

[isv]
name = "ISV"
desc = "Independent Software Vendor"

[ieee]
name = "IEEE"
desc = "Institute of Electrical and Electronics Engineers"

[inria]
name = "INRIA"
desc = "French Institute for Research in Computer Science and Automation"

[isbn]
name = "ISBN"
desc = "International Standard Book Number"
see = ['ISSN']

[issn]
name = "ISSN"
desc = "International Standard Serial Number"
see = ['ISBN']

[ike]
name = "IKE"
desc = "Internet Key Exchange"

[icann]
name = "ICANN"
desc = "The Internet Corporation for Assigned Names and Numbers"

[idc]
name = "IDC"
desc = "Internet Data Center"

[it]
name = "IT"
desc = "Information Technology"
see = "CT" 


[ict]
name = "ICT"
desc = "Information and Communications Technology"
see = ["IT","CT"]

[iana]
name = "IANA"
desc = "Internet Assigned Numbers Authority"

[iso]
name = "ISO"
desc = "International Organization for Standardization"

[iec]
name = "IEC"
desc = "International Electrotechnical Commission"

[isl]
name = "isl"
desc = "Integer Set Library (used by GCC)"

[ip.semiconductor]
name = "IP core"
desc = "Intellectual Property core"

[idf.espressif]
name = "Espressif IDF"
desc = "IoT Development Framework"

[i2c]
name = "I2C"
desc = "Inter-Integrated Circuit"

[irq]
name = "IRQ"
desc = "Interrupt Request"

[ime]
name = "IME"
desc = "Input Method Engine"

[ibus]
name = "IBus"
desc = "Intelligent Input Bus"
see = ['Fcitx']

[ic]
name = "IC"
desc = "Integrated Circuits"

[its]
name = "ITS"
desc = "Incompatible Timesharing System operating system "

[isa]
name = "ISA"
desc = "Instruction Set Architecture"

[isc]
name = "ISC license"
desc = "Internet Systems Consortium license"

[ioccc]
name = "IOCCC"
desc = "International Obfuscated C Code Contest"

[ide.software]
name = "IDE"
desc = "Integrated Development Environment"

[ide.hardware]
name = "IDE"
desc = "Integrated Drive Electronics"
more = "A type of cable that is used to connect to the motherboard directly. It's the first version of what is now called the ATA/ATAPI, developed by Western Digital"
see = ['ATA']

[iot]
name = "IOT"
desc = "Internet of Things"

[ip.network]
name = "IP"
desc = "Internet Protocol"

[im.software]
name = "IM"
desc = "Instant Messaging software"

[ielr]
name = "IELR"
desc = "Inadequacy Elimination LR"
see = ['LR', 'LALR']

[ipfs]
name = "IPFS"
desc = "InterPlanetary File System"

[ir]
name = "IR"
desc = "Intermediate Representation"

[ibm]
name = "IBM"
desc = "International Business Machines Corporation"

[iswim]
name = "ISWIM"
desc = "If you See What I Mean"
more = "An abstract computer programming language (or a family of languages) devised by Peter Landin and first described in his article 'The Next 700 Programming Languages', published in the Communications of the ACM in 1966"

[ipc]
name = "IPC"
desc = "Inter-Process Communication"

[ial]
name = "IAL"
desc = "Internatinal Algebraic Language"
see = ['ALGOL']

[i18n]
name = "i18n"
desc = """internationalization
         ^^^^^^^^^^^^^^^^^^
              18 chars"""
see = ['L10n','m17n']

[ics]
name = "ICS for ISO"
desc = "ISO - International Classification for Standards"

[iam]
name = "IAM"
desc = "Identity and Access Management"

[itu]
name = "ITU"
desc = "International Telecommunication Union"

[imap]
name = "IMAP"
desc = "Internet Message Access Protocol"

[iocp]
name = "IOCP"
desc = "Input/output completion port"
more = "An API for performing multiple simultaneous asynchronous input/output operations in Windows NT versions 3.5 and later, AIX and on Solaris 10 and later. It's the kernel event notification mechanism like kqueue or (e)poll"

[icmp]
name = "ICMP"
desc = "Internet Control Message Protocol"

[ido.Emacs]
name = "Ido mode in Emacs"
desc = "Interactively DO things"

[idpf]
name = "IDPF"
desc = "International Digital Publishing Forum"

[icp]
name = "ICP"
desc = "Internet Content Provider"

[iis]
name = "IIS"
desc = "Internet Information Services"
more = "An extensible web server software created by Microsoft for use with the Windows NT family"

[iac]
name = "IaC"
desc = "Infrastructure as Code"

[icc]
name = "ICC"
desc = "Intel C++ Compiler"

[isp]
name = "ISP"
desc = "Internet Service Provider"

[ispd]
name = "ISPD"
desc = "International Symposium on Physical Design"
more = "A yearly conference on the topic of electronic design automation"

[iccad]
name = "ICCAD"
desc = "International Conference on Computer-Aided Design "
