[ietf]
disp = "IETF"
desc = "Internet Engineering Task Force"

[ico]
disp = "ICO"
desc = "Icon image format for Windows"
see = ["CUR"]

[isv]
disp = "ISV"
desc = "Independent Software Vendor"

[ieee]
disp = "IEEE"
desc = "Institute of Electrical and Electronics Engineers"

[inria]
disp = "INRIA"
desc = "French Institute for Research in Computer Science and Automation"

[isbn]
disp = "ISBN"
desc = "International Standard Book Number"
see = ['ISSN']

[issn]
disp = "ISSN"
desc = "International Standard Serial Number"
see = ['ISBN']

[ike]
disp = "IKE"
desc = "Internet Key Exchange"

[icann]
disp = "ICANN"
desc = "The Internet Corporation for Assigned Names and Numbers"

[idc]
disp = "IDC"
desc = "Internet Data Center"

[it]
disp = "IT"
desc = "Information Technology"
see = "CT" 


[ict]
disp = "ICT"
desc = "Information and Communications Technology"
see = ["IT","CT"]

[iana]
disp = "IANA"
desc = "Internet Assigned Numbers Authority"

[iso]
disp = "ISO"
desc = "International Organization for Standardization"

[iec]
disp = "IEC"
desc = "International Electrotechnical Commission"

[isl]
disp = "isl"
desc = "Integer Set Library (used by GCC)"

[ip.semiconductor]
disp = "IP core"
desc = "Intellectual Property core"

[idf.espressif]
disp = "Espressif IDF"
desc = "IoT Development Framework"

[i2c]
disp = "I2C"
desc = "Inter-Integrated Circuit"

[irq]
disp = "IRQ"
desc = "Interrupt Request"

[ime]
disp = "IME"
desc = "Input Method Engine"

[ibus]
disp = "IBus"
desc = "Intelligent Input Bus"
see = ['Fcitx']

[ic]
disp = "IC"
desc = "Integrated Circuits"

[its]
disp = "ITS"
desc = "Incompatible Timesharing System operating system "

[isa]
disp = "ISA"
desc = "Instruction Set Architecture"

[isc]
disp = "ISC license"
desc = "Internet Systems Consortium license"

[ioccc]
disp = "IOCCC"
desc = "International Obfuscated C Code Contest"

[ide.software]
disp = "IDE"
desc = "Integrated Development Environment"

[ide.hardware]
disp = "IDE"
desc = "Integrated Drive Electronics"
full = "A type of cable that is used to connect to the motherboard directly. It's the first version of what is now called the ATA/ATAPI, developed by Western Digital"
see = ['ATA']

[iot]
disp = "IOT"
desc = "Internet of Things"

[ip.network]
disp = "IP"
desc = "Internet Protocol"

[im.software]
disp = "IM"
desc = "Instant Messaging software"

[ielr]
disp = "IELR"
desc = "Inadequacy Elimination LR"
see = ['LR', 'LALR']

[ipfs]
disp = "IPFS"
desc = "InterPlanetary File System"

[ir]
disp = "IR"
desc = "Intermediate Representation"
