[jpeg]
disp = "JPEG"
desc = "Joint Photographic Experts Group"
full = "Introduced in 1992. A commonly used method of lossy compression for digital images"

[jpg]
same = "JPEG<=>jpeg"

[jif]
disp = "JIF"
desc = "JPEG Interchange Format"
full = "This pure file format is rarely used, primarily because of the difficulty of programming encoders and decoders that fully implement all aspects of the standard and because of certain shortcomings of the standard"

[jfif]
disp = "JFIF"
desc = "JPEG File Interchange Format"
full = "Released in 1992. It defines supplementary specifications for the container format that contains the image data encoded with the JPEG algorithm."

[jam]
disp = "JAM"
desc = "JavaScript, APIs, Markup stack"

[jsr]
disp = "JSR"
desc = "Java Specification Requests"

[jpl]
disp = "JPL"
desc = "NASA Jet Propulsion Laboratory"

[jdt.eclipse]
disp = "JDT"
desc = "Eclipse Java Development Tools"

[jit]
disp = "JIT"
desc = "Just in Time Compilation"
see = ['AOT']

[js]
disp = "JS"
desc = "JavaScript"

[json]
disp = "JSON"
desc = "JavaScript Object Notation"

[jsp]
disp = "JSP"
desc = "Java Server Pages"

[jar]
disp = "JAR"
desc = "Java ARchive"

[jdk]
disp = "JDK"
desc = "Java Development Kit"
see = ['JRE']

[jre]
disp = "JRE"
desc = "Java Runtime Environment"
see = ['JDK']

[jvm]
disp = "JVM"
desc = "Java Virtual Machine"

[j2me]
disp = "J2ME"
desc = "Java Platform, Micro Edition"
see = ['J2SE']

[j2se]
disp = "J2SE"
desc = "Java Platform, Standard Edition"
see = ['J2ME']

[jflap]
disp = "JFLAP"
desc = "Java Formal Languages and Automata Package"

[jsx]
disp = "JSX"
desc = "JavaScript Extension"
full = "A React extension which allows writing JavaScript code that looks like HTML"
