[kms]
disp = "KMS"
desc = "Kernel Mode Setting"

[kvm]
disp = "KVM"
desc = "Kernel-based Virtual Machine"
full ="A full virtualization solution for Linux on x86 hardware containing virtualization extensions (Intel VT or AMD-V). It consists of a loadable kernel module, kvm.ko, that provides the core virtualization infrastructure and a processor specific module, kvm-intel.ko or kvm-amd.ko."

[kqueue]
disp = "kqueue"
desc = "kernel queue"
full = "A scalable event notification interface introduced in FreeBSD 4.1 on July 2000, also supported in NetBSD, OpenBSD, DragonFly BSD, and macOS. "
see = ['epoll', 'IOCP']
