[mime]
disp = "MIME"
desc = "Multipurpose Internet Mail Extensioin"
full = "It is an Internet standard that extends the format of email messages to support text in character sets other than ASCII， as well as attachments of audio， video， images， and application programs."

[mpeg]
disp = "MPEG"
desc = "Moving Picture Experts Group"

[mp4]
disp = "MP4"
desc = "MPEG-4"
full = "Introduced in late 1998"
see = ["MPEG"]

[mp3]
disp = "MP3"
desc = "MPEG-3"
see = ["MPEG"]

[mda]
disp = "MDA"
desc = "Model Driven Architecture"

[mop]
disp = "MOP"
desc = "Common Lisp MetaObject Protocol"
see = ['CLOS']

[melpa]
disp = "MELPA"
desc = "Milkypostman’s Emacs Lisp Package Archive"

[m-expression]
disp = "M-expression"
desc = "Meta expression"

[mac.MIT]
disp = "MAC(MIT)"
desc = "the Project on Mathematics and Computation"

[mingw]
disp = "MinGW"
desc = "Minimalist GNU for Windows"

[msys]
disp = "MSYS2"
desc = "minimal system 2"

[msvc]
disp = "MSVC"
desc = "Microsoft C++"

[mri]
disp = "MRI"
desc = "Matz's Ruby Interpreter"

[mpfr]
disp = "GNU MPFR"
desc = "The GNU Multiple Precision Floating-Point Reliable Library"
full = "based on GNU MP library"
see = ['GMP']

[mpc]
disp = "MPC"
desc = "Multiple Precision C library"
full = "based on GNU MPFR, for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result"
see = ['MPFR']

[msp430]
disp = "MSP430"
desc = "TI mixed-signal microcontroller family"
full = "First introduced on 14 February 1992. Built around a 16-bit CPU"
