[mime]
name = "MIME"
desc = "Multipurpose Internet Mail Extensioin"
more = "It is an Internet standard that extends the format of email messages to support text in character sets other than ASCII， as well as attachments of audio， video， images， and application programs."

[mpeg]
name = "MPEG"
desc = "Moving Picture Experts Group"

[mkv]
name = "MKV"
desc = "Matroska file for video (which may include subtitles or audio)"
more = "A project and an open standard to create a container format that can hold an unlimited number of video, audio, picture, or subtitle tracks in one file"

[mp4]
name = "MP4"
desc = "MPEG-4"
more = "Introduced in late 1998"
see = ["MPEG"]

[mp3]
name = "MP3"
desc = "MPEG-3"
see = ["MPEG"]

[mda]
name = "MDA"
desc = "Model Driven Architecture"

[mop]
name = "MOP"
desc = "Common Lisp MetaObject Protocol"
see = ['CLOS']

[melpa]
name = "MELPA"
desc = "Milkypostman’s Emacs Lisp Package Archive"
see = ['elpa']

[m-expression]
name = "M-expression"
desc = "Meta expression"

[mac.MIT]
name = "MAC(MIT)"
desc = "the Project on Mathematics and Computation"

[mingw]
name = "MinGW"
desc = "Minimalist GNU for Windows"

[msys]
name = "MSYS2"
desc = "minimal system 2"

[mri]
name = "MRI"
desc = "Matz's Ruby Interpreter"

[mjit]
name = "MJIT"
desc = "Method Based Just-in-time Compiler for Ruby"
see = ['YJIT']

[mpfr]
name = "GNU MPFR"
desc = "The GNU Multiple Precision Floating-Point Reliable Library"
more = "based on GNU MP library"
see = ['GMP']

[mpc]
name = "MPC"
desc = "Multiple Precision C library"
more = "based on GNU MPFR, for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result"
see = ['MPFR']

[mt]
name = "MT"
desc = "Multithreading"

[mpu]
name = "MPU"
desc = "Memory Protection Unit"
more = "MPU is a trimmed down version of MMU providing only memory protection support"

[mmu]
name = "MMU"
desc = "Memory Management Unit"

[mpp]
name = "MPP"
desc = "Massively Parallel Processing"

[misra]
name = "MISRA"
desc = "Motor Industry Software Reliability Association"

[mfa]
name = "MFA"
desc = "Multi-factor Authentication"
see = ['2FA']

[mpi]
name = "MPI"
desc = "Message Passing Interface"
more = "A standardized and portable message-passing standard designed to function on parallel computing architectures in C, C++, and Fortran."

[mos]
name = "MOS"
desc = "Metal–Oxide–Semiconductor"

[mips]
name = "MIPS"
desc = "Microprocessor without Interlocked Pipelined Stages"
more = "a RISC instruction set architecture"
see = ['RISC']

[mdn]
name = "MDN"
desc = "Mozilla Developer Network"

[mi.gdb]
name = "MI"
desc = "gdb Machine Interface specification"
more = "GDB and LLDB use this"
see = ['GDB']

[mqtt]
name = "MQTT"
desc = "Message Queueing Telemetry Transport"
more = "A lightweight, publish-subscribe network protocol that transports messages between devices"

[mlir]
name = "MLIR"
desc = "Multi-Level Intermediate Representation"

[mvc]
name = "MVC"
desc = "Model-View-Controller"
see = 'MVP'

[mvp]
name = "MVP"
desc = "Model–View–Presenter"
more = """A derivation of the model–view–controller (MVC) architectural pattern, and is used mostly for building user interfaces. In MVP, the presenter assumes the functionality of the "middle-man". In MVP, all presentation logic is pushed to the presenter."""
see = 'MVC'

[mvvm]
name = "MVVM"
desc = "Model View ViewModel"

[multics]
name = "Multics"
desc = "Multiplexed Information and Computing Service"
more = "An influential early time-sharing operating system based on the concept of a single-level memory"
see = ['Unix']

[m17n]
name = "m17n"
desc = """multilingualization
         ^^^^^^^^^^^^^^^^^
              17 chars"""
more = "A free software library for any GNU-Linux/Unix applications to realize multilingualization of many aspects of applications"
see = ['i18n','L10n']

[m2e]
name = "m2e"
desc = "maven support in Eclipse"

[magit.Emacs]
name = "Magit"
desc = "Magical Git"
more = "Most popular Git client for Emacs"

[m4]
name = "m4"
desc = "a general-purpose macro processor"
more = """The language was designed by Brian Kernighan and Dennis Ritchie for the original versions of UNIX. It is an extension of an earlier macro processor, m3, written by Ritchie for an unknown AP-3 minicomputer.

  The macro preprocessor operates as a text-replacement tool. It is employed to re-use text templates, typically in computer programming applications, but also in text editing and text-processing applications. Most users require m4 as a dependency of GNU autoconf. """

[mvn]
name = "mvn"
desc = "maven"
more = "A build automation tool used primarily for Java projects"

[md5]
name = "MD5"
desc = "Message-Digest function 5"
more = "A cryptographically broken but still widely used hash function producing a 128-bit hash value, designed by Ronald Rivest in 1991 to replace an earlier hash function MD4"

[mimd]
name = "MIMD"
desc = "Multiple instruction, Multiple data"

[mac]
name = "MAC"
desc = "Media Access Control address"

[msb.bit]
name = "MSB"
desc = "Most Significant Bit"
see = ['LSB']

[mqueue]
name = "mqueue"
desc = "message queue on Linux"

[midi]
name = "MIDI"
desc = "Musical Instrument Digital Interface"

[meid]
name = "MEID"
desc = "Mobile Equipment Identifier"

[motd]
name = "/etc/motd"
desc = "message of the day"
more = "A file on Unix-like CLI systems. The contents of the file /etc/motd are displayed by the Unix login command after a successful login, and just before it executes the login shell"

[mbd]
name = "MBD"
desc = "Model-based Design"

[mcad]
name = "MCAD"
desc = "Mechanical Computer-Aided Design"
see = 'ECAD'

[mmc]
name = "MMC"
desc = "MultiMedia Card"

[mbr]
name = "MBR"
desc = "Master Boot Record"

[moba]
name = "MOBA"
desc = "Multiplayer Online Battle Arena"

[moc]
name = "moc in Qt"
desc = "meta object compiler"
see = ['uic', 'rcc']

[mame]
name = "MAME"
desc = "Multiple Arcade Machine Emulator"
more = "A free and open-source emulator designed to recreate the hardware of arcade game systems in software on modern personal computers and other platforms"

[mllm]
name = "MLLM"
desc = "Multilingual Language Model"

[mo]
name = ".MO file"
desc = "Machine Object file"
more = "Compiled, machine-optimized versions of PO files, used directly by software"
see = 'PO'

[maas]
name = "MaaS"
desc = "Model as a Service"
