[mime]
disp = "MIME"
desc = "Multipurpose Internet Mail Extensioin"
full = "It is an Internet standard that extends the format of email messages to support text in character sets other than ASCII， as well as attachments of audio， video， images， and application programs."

[mpeg]
disp = "MPEG"
desc = "Moving Picture Experts Group"

[mp4]
disp = "MP4"
desc = "MPEG-4"
full = "Introduced in late 1998"
see = ["MPEG"]

[mp3]
disp = "MP3"
desc = "MPEG-3"
see = ["MPEG"]

[mda]
disp = "MDA"
desc = "Model Driven Architecture"

[mop]
disp = "MOP"
desc = "Common Lisp MetaObject Protocol"
see = ['CLOS']

[melpa]
disp = "MELPA"
desc = "Milkypostman’s Emacs Lisp Package Archive"

[m-expression]
disp = "M-expression"
desc = "Meta expression"

[mac.MIT]
disp = "MAC(MIT)"
desc = "the Project on Mathematics and Computation"

[mingw]
disp = "MinGW"
desc = "Minimalist GNU for Windows"

[msys]
disp = "MSYS2"
desc = "minimal system 2"

[msvc]
disp = "MSVC"
desc = "Microsoft Visual C++"

[mri]
disp = "MRI"
desc = "Matz's Ruby Interpreter"

[mpfr]
disp = "GNU MPFR"
desc = "The GNU Multiple Precision Floating-Point Reliable Library"
full = "based on GNU MP library"
see = ['GMP']

[mpc]
disp = "MPC"
desc = "Multiple Precision C library"
full = "based on GNU MPFR, for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result"
see = ['MPFR']

[msp430]
disp = "MSP430"
desc = "TI mixed-signal microcontroller family"
full = "First introduced on 14 February 1992. Built around a 16-bit CPU"

[mt]
disp = "MT"
desc = "Multithreading"

[mpu]
disp = "MPU"
desc = "Memory Protection Unit"
full = "MPU is a trimmed down version of MMU providing only memory protection support"

[mmu]
disp = "MMU"
desc = "Memory Management Unit"

[mpp]
disp = "MPP"
desc = "Massively Parallel Processing"

[msix]
disp = "MSIX"
desc = "Microsoft appinstaller"

[misra]
disp = "MISRA"
desc = "Motor Industry Software Reliability Association"

[mfa]
disp = "MFA"
desc = "Multi-factor Authentication"
see = ['2FA']

[mpi]
disp = "MPI"
desc = "Message Passing Interface"
full = "A standardized and portable message-passing standard designed to function on parallel computing architectures in C, C++, and Fortran."

[mos]
disp = "MOS"
desc = "Metal–Oxide–Semiconductor"

[mips]
disp = "MIPS"
desc = "Microprocessor without Interlocked Pipelined Stages"
full = "a RISC instruction set architecture"
see = ['RISC']

[mdn]
disp = "MDN"
desc = "Mozilla Developer Network"

[mi.gdb]
disp = "MI"
desc = "gdb Machine Interface specification"
full = "GDB and LLDB use this"
see = ['GDB']

[mqtt]
disp = "MQTT"
desc = "Message Queueing Telemetry Transport"
full = "A lightweight, publish-subscribe network protocol that transports messages between devices"

[mlir]
disp = "MLIR"
desc = "Multi-Level Intermediate Representation"

[mvc]
disp = "MVC"
desc = "Model-View-Controller"

[mvvw]
disp = "MVVW"
desc = "Model View ViewModel"

[multics]
disp = "Multics"
desc = "Multiplexed Information and Computing Service"
full = "An influential early time-sharing operating system based on the concept of a single-level memory"
see = ['Unix']
