[nvidia]
name = "Nvidia"
desc = "Invidia, Latin for envy"
more = "A company designs GPU. Envy and vision are closely tied in mythology with the eye or the gaze being a common symbol. In addition, sounds being quite similar to video."

[nvd]
name = "NVD"
desc = "National Vulnerability Database"

[nfs]
name = "NFS"
desc = "Network File System"

[ntp]
name = "NTP"
desc = "Network Time Protocol"

[nasm]
name = "nasm"
desc = "Netwide Assembler"

[nptl]
name = "NPTL"
desc = "Native POSIX Thread Library"
more = "An implementation of the POSIX Threads specification for the Linux operating system."

[nes]
name = "NES"
desc = "Nintendo Entertainment System"

[ndk]
name = "NDK"
desc = "The Android Native Development Kit"

[nfa]
name = "NFA"
desc = "Non-deterministic Finite Automata"
see = ['DFA']

[nlp]
name = "NLP"
desc = "Natural Language Processing"

[nfc]
name = "NFC"
desc = "Near-field communication"

[nif.erlang]
name = "NIF"
desc = "Native Implemented Functions in Erlang"

[nas]
name = "NAS"
desc = "Network-attached Storage"

[np]
name = "NP"
desc = "Non-deterministic Polynomial-time"

[ni]
name = "NI"
desc = "National Instruments"

[nist]
name = "NIST"
desc = "National Institute of Standards and Technology"

[nginx]
name = "Nginx"
desc = "engine X"
more = "Initial release on October 2004"

[nntp]
name = "NNTP"
desc = "Network News Transfer Protocol"

[ndp]
name = "NDP"
desc = "Neighbor Discovery Protocol"

[nis]
name = "NIS"
desc = "Network Information Service"
more = "Originally called Yellow Pages or YP. It's a clientâ€“server directory service protocol for distributing system configuration data such as user and host names between computers on a computer network. Over time other modern and secure distributed directory systems, most notably Lightweight Directory Access Protocol (LDAP), came to replace it"

[nss]
name = "NSS"
desc = "Name Service Switch"
more = "The Name Service Switch configuration file is /etc/nsswitch.conf"

[nvm]
name = "NVM"
desc = "NodeJS Version Manager"

[nio]
name = "NIO"
desc = "Non-blocking I/O"

[nvm.memory]
name = "NVM"
desc = "Non-Volatile Memory"

[nvme]
name = "NVME"
desc = "NVM Express or Non-Volatile Memory Express"

[nat]
name = "NAT"
desc = "Network Address Translation"

[nroff]
name = "nroff"
desc = "new roff"
see = ['roff', 'troff']

[ndbm]
name = "ndbm"
desc = "new dbm"

[npu]
name = "NPU"
desc = "Neural Processing Unit"

[nuc]
name = "NUC"
desc = "Next Unit of Computing"
more = "A line of small-form-factor barebone computer kits designed by Intel. It was launched in early 2013"

[nan]
name = "NaN"
desc = "Not a Number"

[npcap]
name = "Npcap"
desc = "Nmap's pcap"
more = "Npcap is the Nmap Project's packet capture (and sending) library for Microsoft Windows"
see = ['Nmap', 'pcap']

[nmap]
name = "Nmap"
desc = "Network Mapper"
more = "A network scanner created in 1997 used to discover hosts and services on a computer network by sending packets and analyzing the responses"

[nmi]
name = "NMI"
desc = "Non-Maskable Interrupt"

[na1]
name = "NA1"
desc = "Normative Addendum 1"
more = "An addition to the C Standard ratified in 1995"

[ns]
name = "NS_"
desc = "NextStep"
more = "The original code for the Cocoa frameworks came from the NeXTSTEP libraries Foundation and AppKit. NextStep engineers chose to prefix their symbols with NS_"

[nqp]
name = "NQP"
desc = "Not Quite Perl"
more = "A lightweight Raku-like environment for virtual machines"
