[od]
name = "od"
desc = "Octal file Dump"

[oci]
name = "OCI"
desc = "Open Container Initiative"

[oem]
name = "OEM"
desc = "Original Equipment Manufacturer"

[otp.erlang]
name = "OTP"
desc = "Open Telecom Platform"

[opencl]
name = "OpenCL"
desc = "Open Computing Language"
more = "Initially developed by Apple Inc in 2008"

[opengl]
name = "OpenGL"
desc = "Open Graphics Library"
more = "API for rendering 2D and 3D vector graphics. The API is corss-language, corss-platform and typically used to interact with a GPU, to achieve the hardware-accelerated rendering"

[opengles]
name = "OpenGL ES"
desc = "OpenGL for Embedded Systems"

[oopsla]
name = "OOPSLA"
desc = "Object-Oriented Programming, Systems, Languages & Applications"

[ofx]
name = "OFX"
desc = "Open Financial Exchange"
more = "It's a data-stream format for exchanging financial information that evolved from Microsoft's Open Financial Connectivity (OFC) and Intuit's Open Exchange file formats."
see = ["QIF"]

[odbc]
name = "ODBC"
desc = "Open Database Connectivity"

[oled]
name = "OLED"
desc = "Organic light-emitting Diode"

[ocr]
name = "OCR"
desc = "Optical Character Recognition"

[orm]
name = "ORM"
desc = "Object Relational Mapper"
see = ['ODM']

[odm]
name = "ODM"
desc = "Object Document Mapper"
see = ['ORM']

[otf]
name = ".otf"
desc = "OpenType Font"
see = ['ttf']

[openmp]
name = "OpenMP"
desc = "Open Multi-Processing"

[osgi.Java]
name = "OSGI"
desc = "Open Services Gateway initiative"
more = "The OSGi specification describes a modular system and a service platform for the Java programming language that implements a complete and dynamic component model, something that does not exist in standalone Java/VM environments."

[org.Emacs]
name = "Org-mode"
desc = "Organizing Mode within Emacs"
more = "Created by Carsten Dominik in 2003, originally to organize his own life and work, and since the first release numerous other users and developers have contributed to this free software package. Emacs has included Org-mode as a major mode by default since 2006"

[omr.Eclipse]
name = "OMR"
desc = "(maybe) Open virtual Machine Runtime"
more = "C and C++ components that can be used to build robust language runtimes, on which OpenJ9 is built"

[osdn]
name = "OSDN"
desc = "Open Source Development Network"
more = "formerly SourceForge.JP"

[otp.password]
name = "OTP"
desc = "One-Time Password"

[openocd]
name = "OpenOCD"
desc = "Open On-Chip Debugger"

[opml]
name = "OPML"
desc = "Outline Processor Markup Language"
more = "An XML format for outlines used for RSS"
see = ['RSS']

[oss]
name = "OSS"
desc = "Open-Source Software"

[osi]
name = "OSI"
desc = "Open Source Initiative"

[osi.network]
name = "OSI"
desc = "Open Systems Interconnection model"
more = "A conceptual model that 'provides a common basis for the coordination of ISO standard development from the purpose of system interconnection"

[osd]
name = "OSD"
desc = "Open Source Definition"

[os]
name = "OS"
desc = "Operating System"

[obs]
name = "OBS"
desc = "openSUSE Build Service"
more = "https://build.opensuse.org/"

[olap]
name = "OLAP"
desc = "Online Analytical Processing"

[ota]
name = "OTA"
desc = "Over-the-air Programming"
more = "Various methods of distributing new software, configuration settings, and so on"

[odf]
name = "ODF"
desc = "Open Document Format"

[oid.Git]
name = "OID"
desc = "Git Object ID"

[osdi]
name = "OSDI"
desc = "Operating Systems Design and Implementation"

[opam]
name = "opam"
desc = "OCaml Package Manager"

[openssf]
name = "OpenSSF"
desc = "Open Source Security Foundation"

[ooad]
name = "OOAD"
desc = "Object-oriented Analysis and Design"

[omg]
name = "OMG"
desc = "Object Management Group"

[opc]
name = "OPC"
desc = "Open Platform Communications"
