[od]
disp = "od"
desc = "Octal file Dump"

[ole]
disp = "OLE"
desc = "Object Linking and Embedding"
full = "A proprietary technology developed by Microsoft that allows embedding and linking to documents and other objects"

[oci]
disp = "OCI"
desc = "Open Container Initiative"

[oem]
disp = "OEM"
desc = "Original Equipment Manufacturer"

[otp]
disp = "OTP"
desc = "Open Telecom Platform"

[opencl]
disp = "OpenCL"
desc = "Open Computing Language"

[opengl]
disp = "OpenGL"
desc = "Open Graphics Library"
full = "API for rendering 2D and 3D vector graphics. The API is corss-language, corss-platform and typically used to interact with a GPU, to achieve the hardware-accelerated rendering"

[oopsla]
disp = "OOPSLA"
desc = "Object-Oriented Programming, Systems, Languages & Applications"

[ofx]
disp = "OFX"
desc = "Open Financial Exchange"
full = "It's a data-stream format for exchanging financial information that evolved from Microsoft's Open Financial Connectivity (OFC) and Intuit's Open Exchange file formats."
see = ["QIF"]

[odbc]
disp = "ODBC"
desc = "Open Database Connectivity"

[oled]
disp = "OLED"
desc = "Organic light-emitting Diode"

[ocr]
disp = "OCR"
desc = "Optical Character Recognition"

[orm]
disp = "ORM"
desc = "Object Relational Mapper"
