[od]
desc = "Octal file Dump"

[OLE]
desc = "Object Linking and Embedding"
full = "A proprietary technology developed by Microsoft that allows embedding and linking to documents and other objects"

[OCI]
desc = "Open Container Initiative"

[OEM]
desc = "Original Equipment Manufacturer"

[OTP]
desc = "Open Telecom Platform"

[OpenCL]
desc = "Open Computing Language"

[OpenGL]
desc = "Open Graphics Library"
full = "API for rendering 2D and 3D vector graphics. The API is corss-language, corss-platform and typically used to interact with a GPU, to achieve the hardware-accelerated rendering"

[OOPSLA]
desc = "Object-Oriented Programming, Systems, Languages & Applications"