[PNG]
desc = "Portable Network Graphics or PNG is Not GIF"
full = "Published in 1997. It's a raster-graphics file format that supports lossless data compression, and was invented to transfer images on the Internet, not for professional-quality print graphics, and as an improved, non-patented replacement for GIF"

[PIC]
desc = "Position Independent Code"

[PSS]
desc = "Proportional Set Size"
see = ['RSS']

[PMID]
desc = "PubMed Unique Identifier"