[png]
name = "PNG"
desc = "Portable Network Graphics or PNG is Not GIF"
more = "Published in 1997. It's a raster-graphics file format that supports lossless data compression, and was invented to transfer images on the Internet, not for professional-quality print graphics, and as an improved, non-patented replacement for GIF"

[pic.hardware]
name = "PIC"
desc = "Programmable Interrupt Controller"
see = 'APIC'

[pic.code]
name = "PIC"
desc = "Position Independent Code"

[pss]
name = "PSS"
desc = "Proportional Set Size"
see = ['RSS']

[pmid]
name = "PMID"
desc = "PubMed Unique Identifier"

[pv]
name = "PV"
desc = "Paravirtual"

[pgo]
name = "PGO"
desc = "Profile Guided Optimization"

[posix]
name = "POSIX"
desc = "Portable Operating System Interface"

[psoc]
name = "PSoC"
desc = "Programmable System on a Chip"

[pkm]
name = "PKM"
desc = "Personal Knowledge Management"

[pep.python]
name = "PEP"
desc = "Python Enhancement Proposals"

[pdo.php]
name = "PDO"
desc = "PHP Data Objects"
more = "It provides a clear, simple, unified API for working with databases"

[peg]
name = "PEG"
desc = "Parsing Expression Grammar"

[plc]
name = "PLC"
desc = "Programmable Logic Controller"

[paas]
name = "PAAS"
desc = "Platform As A Service"

[pcc]
name = "PCC"
desc = "Portable C Compiler"

[prom]
name = "PROM"
desc = "Programmable Read-only Memory"
see = ['ROM']

[pmd]
name = "PMD"
desc = "Programming Mistake Detector"
more = "A code analyzer for Java"

[pata]
name = "PATA"
desc = "Parallel ATA"
see = ['SATA', 'ATA']

[pwa]
name = "PWA"
desc = "Progressive Web Application"

[pdf]
name = "PDF"
desc = "Portable Document Format"

[pn]
name = "PN"
desc = "Polish Notation"
more = "e.g. (+ 3 4)"
see = ['RPN']

[pldi.ACMcon]
name = "PLDI"
desc = "Programming Language Design and Implementation"

[plop.ACMcon]
name = "PLOP"
desc = "Pattern Languages of Programs"

[popl.ACMcon]
name = "POPL"
desc = "Principles of Programming Languages"

[pda]
name = "PDA"
desc = "Personal Digital Assistant"

[pda.auto]
name = "PDA"
desc = "Pushdown Automaton"

[pci]
name = "PCI"
desc = "Peripheral Component Interconnect"

[pcie]
name = "PCIe"
desc = "PCI Express"

[post]
name = "POST"
desc = "power-on self-test"

[p2p]
name = "P2P"
desc = "Peer-to-Peer"

["pl/i"]
name = "PL/I"
desc = "Programming Language One"
more = "It's the implementation language of Multics. A procedural, imperative computer programming language developed and published by IBM. It is designed for scientific, engineering, business and system programming. It has been used by academic, commercial and industrial organizations since it was introduced in the 1960s, and is still used. "

["pl/0"]
name = "PL/0"
desc = "Programming Language Zero"
more = "An educational programming language, that is similar to but much simpler than PascalIt was originally introduced in the book, Algorithms + Data Structures = Programs, by Niklaus Wirth in 1976"

["pl/sql"]
name = "PL/SQL"
desc = "Procedural Language for SQL"
more = "It's Oracle Corporation's procedural extension for SQL"
see = ['SQL']

[pdp]
name = "PDP"
desc = "Programmed Data Processor"
more = "A term used by the Digital Equipment Corporation from 1957 to 1990 for several lines of minicomputers"
see = ['PDP-7', 'PDP-11']

[pdp-7]
name = "PDP-7"
desc = "Programmed Data Processor 7"
more = "Introduced in 1964, The first version of Unix, and the first version of B were written for the PDP-7 at Bell Labs"
see = ['PDP-11']

[pdp-11]
name = "PDP-11"
desc = "Programmed Data Processor 11"
more = "16-bit, its successor is VAX"
see = ['PDP-7','VAX']

[perf]
name = "perf"
desc = "performance analyzing tool in Linux"

[pdb.python]
name = "pdb"
desc = "The Python Debugger"

[po]
name = ".PO file"
desc = "portable object file, text-based"

[pgp]
name = "PGP"
desc = "Pretty Good Privacy"
more = "OpenPGP refers to the OpenPGP protocol"

[php]
name = "PHP"
desc = "PHP: Hypertext Preprocessor"
more = "originally stood for Personal Home Page"

[perl]
name = "Perl"
desc = "Practical Extraction and Reporting Language"

[perlref.Perl]
name = "perlref"
desc = "Perl references and nested data structures"

[perlop.Perl]
name = "perlop"
desc = "Perl operators and precedence"

[perlre.Perl]
name = "perlre"
desc = "Perl regular expressions"

[pcre]
name = "PCRE"
desc = "Perl Compatible Regular Expressions"

[pod]
name = "POD"
desc = "Plain Old Documentation"
more = "A lightweight markup language used to document the Perl programming language as well as Perl modules and programs."

[ppo3]
name = "POP3"
desc = "Post Office Protocol 3"

[pypi]
name = "PyPI"
desc = "The Python Package Index"

[pki]
name = "PKI"
desc = "Public Key Infrastructure"

[pkcs]
name = "PKCS"
desc = "Public Key Cryptography Standards"

[pom]
name = "POM"
desc = "Project Object Model"

[ppa.Ubuntu]
name = "PPA"
desc = "Personal Package Archive"

[pgi]
name = "PGI"
desc = "The Portland Group, Inc"
more = "A company that produced a set of commercially available Fortran, C and C++ compilers for high-performance computing systems. On July 29, 2013, Nvidia acquired The Portland Group, Inc."

[pypa]
name = "pypa"
desc = "Python Packaging Authority"

[pip]
name = "pip"
desc = "Package Installer for Python"

[pos]
name = "PoS"
desc = "Proof of Stake"
more = "This is done to avoid the computational cost of proof of work schemes"
see = ['PoW']

[pow]
name = "PoW"
desc = "Proof of Work"
more = "A class of consensus mechanisms for blockchains"
see = ['PoS']

[pwm]
name = "PWM"
desc = "Pulse-Width Modulation"

[pem]
name = "PEM"
desc = "Privacy Enhanced Mail"
more = "originally developed to secure mail in the 1990s but was never widely adopted. Instead, the PEM container was re-purposed for storing certificate-related information."

[pam]
name = "PAM"
desc = "Linux Pluggable Authentication Modules"

[paru.Arch]
name = "paru"
desc = "Feature packed AUR helper"
see = ['yay', 'yaourt']

[ppm]
name = "PPM"
desc = "Perl Package Manager"

[pmis]
name = "PMIS"
desc = "Project Management Information System"

[pim]
name = "PIM"
desc = "Personal Information Manager"

[pld]
name = "PLD"
desc = "Programmable Logic Device"

[pine]
name = "Pine"
desc = "Pine Is Not Elm"
more = "An email client that replaced another email client Elm"

[pico]
name = "Pico editor"
desc = "Pine Composer"

["ps/2"]
name = "IBM PS/2"
desc = "IBM Personal System/2"
more = "IBM's second generation of personal computers"
see = ['XT', 'AT']

[ppi]
name = "PPI"
desc = "Pixels Per Inch"
see = 'DPI'

[poc]
name = "PoC"
desc = "Proof of Concept"
see = 'PoV'

[pov]
name = "PoV"
desc = "Proof of Value"
see = 'PoC'

[py]
name = ".py"
desc = "Python files"

[pr]
name = "PR"
desc = "Pull Request"

[pod.Data]
name = "POD"
desc = "Plain Old Data"
more = "It's another term for 'PDS'"
see = 'PDS'

[pds]
name = "PDS"
desc = "Passive Data Structure"
more = "A term for a 'record', to contrast with objects. It is a data structure that is represented only as passive collections of field values (instance variables), without using object-oriented features"

[pimpl]
name = "PIMPL"
desc = "Pointer to IMPLementation in C++"

[pri]
name = ".pri"
desc = "qmake Project Include file"
more = "See: https://doc.qt.io/qtvstools/qtvstools-importing-and-exporting-projects.html"

[pixel]
name = "pixel"
desc = "Picture Elements"

[pv.statistics]
name = "PV"
desc = "Page View"
see = 'UV'

[pcap]
name = "pcap"
desc = "Packet Capture"
more = "An application programming interface for capturing network traffic"

[pojo]
name = "POJO"
desc = "Plain Old Java/JavaScript Object"

[pthreads]
name = "pthreads"
desc = "POSIX Threads"
