[qif]
disp = "QIF"
desc = "Quicken Interchange Format"
full = "It's an open specification for reading and writing financial data to media, it's older than OFX"
see = ["OFX"]

[qps]
disp = "QPS"
desc = "Queries Per Second"

[qa]
disp = "QA"
desc = "Quality Assurance"

[qc]
disp = "QC"
desc = "Quality Control"

[quic]
disp = "QUIC"
desc = "Quick UDP Internet Connections"

[qr]
disp = "QR code"
desc = "Quick Response code"

[qos]
disp = "QoS"
desc = "Quality of Service"
