[qif]
name = "QIF"
desc = "Quicken Interchange Format"
more = "It's an open specification for reading and writing financial data to media, it's older than OFX"
see = ["OFX"]

[qps]
name = "QPS"
desc = "Queries Per Second"

[qa]
name = "QA"
desc = "Quality Assurance"
see = 'QC'

[qc]
name = "QC"
desc = "Quality Control"
see = 'QA'

[quic]
name = "QUIC"
desc = "Quick UDP Internet Connections"

[qr]
name = "QR code"
desc = "Quick Response code"

[qos]
name = "QoS"
desc = "Quality of Service"

[qemu]
name = "QEMU"
desc = "Quick EMUlator"

[qcow]
name = "qcow"
desc = "QEMU Copy On Write"
more = "A file format for disk image files used by QEMU"
see = ['QEMU', 'VDI', 'VMDK']
