[rsa]
disp = "RSA"
desc = "Ron Rivest, Adi Shamir, Leonard Adleman"
full = "They invest the RSA algorithm"

[rfc]
disp = "RFC"
desc = "Request For Comments"

[rle]
disp = "RLE"
desc = "Run Length Encoding (RLE)"
full = "It is a lossless data compression algorithm, supported by many bitmap file formats, like BMP, TIFF and PCX"

[radar]
disp = "Radar"
desc = "Radio Detection And Ranging"

[rup]
disp = "RUP"
desc = "Rational Unified Process"

[rss.memory]
disp = "RSS"
desc = "Resident Set Size"
full = "to show how much real memory is to that process and is resident in RAM now"
see = ['VSZ','PSS']

[rtf]
disp = "RTF"
desc = "Rich Text Format"

[ris]
disp = "RIS"
desc = "A standardized tag format developed by Research Information Systems"
full = "Used by citation management applications like Mendeley, EndNote and so on"

[r5rs]
disp = "R5RS"
desc = "Revised 5 Report on the Algorithmic Language Scheme"

[r6rs]
disp = "R6RS"
desc = "Revised 6 Report on the Algorithmic Language Scheme"

[rts]
disp = "RTS"
desc = "Real-Time Strategy Game"

[rad]
disp = "RAD"
desc = "Rapid Application Development"

[rpm]
disp = "RPM"
desc = "RedHat Package Manager"

[rxvt]
disp = "rxvt"
desc = "Rob's xvt(X Virtual Terminal) or our extended virtual terminal"
full = "a popular replacement for the standard 'xterm'"

[raii]
disp = "RAII"
desc = "Resource Acquisition Is Initialization"

[rtl]
disp = "RTL"
desc = "Runtime Library(in C/C++)"

[rf]
disp = "RF"
desc = "Radio Frequency"

[rss]
disp = "RSS"
desc = "RDF Site Summary or Really Simple Syndication"
see = ['RDF']

[rdf]
disp = "RDF"
desc = "Resource Description Framework"
full = "A W3C standard originally designed as a data model for metadata."

[racc]
disp = "Racc"
desc = "Ruby yACC"
see = ['Yacc']

[rcs]
disp = "RCS"
desc = "Revision Control System"

[risc]
disp = "RISC"
desc = "Reduced Instruction Set Computing"
see = ['CISC']

[ram]
disp = "RAM"
desc = "Random-access Memory"
see = ['ROM']

[rom]
disp = "ROM"
desc = "Read-only Memory"
see = ['RAM', 'PROM', 'EPROM']

[rpg]
disp = "RPG"
desc = "Role-Playing Game"
