[RSA]
desc = "Ron Rivest, Adi Shamir, Leonard Adleman"
full = "They invest the RSA algorithm"

[RFC]
desc = "Request For Comments"

[RLE]
desc = "Run Length Encoding (RLE)"
full = "It is a lossless data compression algorithm, supported by many bitmap file formats, like BMP, TIFF and PCX"

[Radar]
desc = "Radio Detection And Ranging"

[RUP]
desc = "Rational Unified Process"

[RSS]
desc = "Resident Set Size"
full = "to show how much real memory is to that process and is resident in RAM now"
see = ['VSZ','PSS']