[SGML]
desc = "Standard Generalized Markup Language"

[SDDM]
desc = "Simple Desktop Display Manager"
full = "A QML based X11 and Wayland display manager. It is the recommended display manager for the KDE Plasma and LXQt desktop environments."

[SUV]
desc = "Sport Utility Vehicle"

[sbt]
desc = "Scala Build Tool"

[STM]
desc = "Software Transaction Memory"

[s3]
desc = "Amazon Simple Storage Service"

[SNOBOL]
desc = "StriNg Oriented and symBOlic Language"

[SICP]
desc = "Structure and Interpretation of Computer Programs"

[SMART]
desc = "Specific, Measurable, Achievable, Relevant, Time-boxed"

[SLIME]
desc = "The Superior Lisp Interaction Mode for Emacs"

[SVG]
desc = "Scalable Vector Graphics"

[SOAP]
desc = "Simple Object Access Protocol"
full = "a messaging porotocal initially as XML-RPC in June 1998"

[sexp]
desc = "S(ymbolic) expression"

[SRFI]
desc = "Scheme Requests for Implementation"

[SA]
desc = "Security Association"

[SM4]
desc = "a block cipher used in the Chinese National Standard for Wireless LAN WAPI"

[SAS]
desc = "Symbolic Algebra System"