[sgml]
disp = "SGML"
desc = "Standard Generalized Markup Language"

[sddm]
disp = "SDDM"
desc = "Simple Desktop Display Manager"
full = "A QML based X11 and Wayland display manager. It is the recommended display manager for the KDE Plasma and LXQt desktop environments."

[suv]
disp = "SUV"
desc = "Sport Utility Vehicle"

[sbt]
disp = "sbt"
desc = "Scala Build Tool"

[stm]
disp = "STM"
desc = "Software Transaction Memory"

[s3]
disp = "s3"
desc = "Amazon Simple Storage Service"

[snobol]
disp = "SNOBOL"
desc = "StriNg Oriented and symBOlic Language"

[sicp]
disp = "SICP"
desc = "Structure and Interpretation of Computer Programs"

[smart]
disp = "SMART"
desc = "Specific, Measurable, Achievable, Relevant, Time-boxed"

[slime]
disp = "SLIME"
desc = "The Superior Lisp Interaction Mode for Emacs"

[svg]
disp = "SVG"
desc = "Scalable Vector Graphics"

[soap]
disp = "SOAP"
desc = "Simple Object Access Protocol"
full = "a messaging porotocal initially as XML-RPC in June 1998"

[sexp]
disp = "sexp"
desc = "S(ymbolic) expression"

[srfi]
disp = "SRFI"
desc = "Scheme Requests for Implementation"

[sa]
disp = "SA"
desc = "Security Association"

[sm4]
disp = "SM4"
desc = "a block cipher used in the Chinese National Standard for Wireless LAN WAPI"

[sas.algebra]
disp = "SAS"
desc = "Symbolic Algebra System"

[sas.statistics]
disp = "SAS"
desc = "Statistics Analysis System"

[spss]
disp = "SPSS"
desc = "Statistical Product and Service Solutions"
full = "formerly Statistical Package for the Social Sciences, reflecting the original market"

[srgb]
disp = "sRGB"
desc = "standard Red Green Blue"

[stl.3D]
disp = "STL(format)"
desc = "Standard Triangle Language and Standard Tessellation Language"
full = "a file format native to the stereolithography CAD software created by 3D Systems"

[stdin]
disp = "STDIN"
desc = "Standard Input"

[stdout]
disp = "STDOUT"
desc = "Standard Output"

[stderr]
disp = "STDERR"
desc = "Standard Error"

[stl.cpp]
disp = "STL"
desc = "C++ Standard Template Library"

[sigmod]
disp = "SIGMOD"
desc = "The Association for Computing Machinery's Special Interest Group on Management of Data, which specializes in large-scale data management problems and databases."
