[sgml]
disp = "SGML"
desc = "Standard Generalized Markup Language"

[sddm]
disp = "SDDM"
desc = "Simple Desktop Display Manager"
full = "A QML based X11 and Wayland display manager. It is the recommended display manager for the KDE Plasma and LXQt desktop environments."

[suv]
disp = "SUV"
desc = "Sport Utility Vehicle"

[sbt]
disp = "sbt"
desc = "Scala Build Tool"

[stm]
disp = "STM"
desc = "Software Transaction Memory"

[s3]
disp = "s3"
desc = "Amazon Simple Storage Service"

[snobol]
disp = "SNOBOL"
desc = "StriNg Oriented and symBOlic Language"

[sicp]
disp = "SICP"
desc = "Structure and Interpretation of Computer Programs"

[smart]
disp = "SMART"
desc = "Specific, Measurable, Achievable, Relevant, Time-boxed"

[slime]
disp = "SLIME"
desc = "The Superior Lisp Interaction Mode for Emacs"

[svg]
disp = "SVG"
desc = "Scalable Vector Graphics"

[soap]
disp = "SOAP"
desc = "Simple Object Access Protocol"
full = "a messaging porotocal initially as XML-RPC in June 1998"

[sexp]
disp = "sexp"
desc = "S(ymbolic) expression"

[srfi]
disp = "SRFI"
desc = "Scheme Requests for Implementation"

[sa]
disp = "SA"
desc = "Security Association"

[sm4]
disp = "SM4"
desc = "a block cipher used in the Chinese National Standard for Wireless LAN WAPI"

[sas.algebra]
disp = "SAS"
desc = "Symbolic Algebra System"

[sas.statistics]
disp = "SAS"
desc = "Statistics Analysis System"

[spss]
disp = "SPSS"
desc = "Statistical Product and Service Solutions"
full = "formerly Statistical Package for the Social Sciences, reflecting the original market"

[srgb]
disp = "sRGB"
desc = "standard Red Green Blue"

[stl.3D]
disp = ".stl"
desc = "Standard Triangle Language and Standard Tessellation Language"
full = "A file format native to the stereolithography CAD software created by 3D Systems"

[stdin]
disp = "STDIN"
desc = "Standard Input"

[stdout]
disp = "STDOUT"
desc = "Standard Output"

[stderr]
disp = "STDERR"
desc = "Standard Error"

[stl.cpp]
disp = "STL"
desc = "C++ Standard Template Library"

[sigmod]
disp = "SIGMOD"
desc = "The Association for Computing Machinery's Special Interest Group on Management of Data"
full = "which specializes in large-scale data management problems and databases."

[seo]
disp = "SEO"
desc = "Search Engine Optimization"

[sdl]
disp = "SDL"
desc = "Simple DirectMedia Layer"

[sus]
disp = "SUS"
desc = "Single UNIX Specification"

[scm]
disp = "SCM"
desc = "Source Code Management"

[sloc]
disp = "sloc"
desc = "Source Lines of Code"

[smp]
disp = "SMP"
desc = "Symmetrical Multiprocessing"

[smt]
disp = "SMT"
desc = "Simultaneous Multithreaded"

[sram]
disp = "SRAM"
desc = "Static Random-Access Memory"

[smbios]
disp = "SMBIOS"
desc = "System Management BIOS"

[st]
disp = "ST"
desc = "SGS Microelettronica and Thomson Semiconducteurs"
full = "The company resulted from the merger of two government-owned semiconductor companies in 1987: Thomson Semiconducteurs of France and SGS Microelettronica of Italy. It is commonly called ST, and it is Europe's largest semiconductor chip maker based on revenue"

[sip]
same = "ip.semiconductor"

[spi]
disp = "SPI"
desc = "Serial Peripheral Interface"

[sd]
disp = "SD"
desc = "Secure Digital"

[spdx]
disp = "SPDX"
desc = "Software Package Data Exchange"

[sast]
disp = "SAST"
desc = "Static Application Security Testing"

[sdlc]
disp = "SDLC"
desc = "Software Development Life Cycle"

[sdd]
disp = "SDD"
desc = "Software Design Description/Document"

[swt.java]
disp = "SWT"
desc = "Standard Widget Toolkit for Java"

[sre]
disp = "SRE"
desc = "Site Reliability Engineer"

[swe]
disp = "SWE"
desc = "Software Engineering"

[soc]
disp = "SoC"
desc = "System on a Chip"

[ssa.llvm]
disp = "SSA"
desc = "Static Single Assignment"
