[tiff]
name = "TIFF"
desc = "Tag Image File Format"

[ti]
name = "TI"
desc = "Texas Instruments"

[tsv]
name = "TSV"
desc = "Tab-separated values"

[tsx]
name = "TSX"
desc = "Transactional Synchronization Extensions"

[tls]
name = "TLS"
desc = "Transport Layer Security"
full = "The successor of the now-deprecated Secure Sockets Layer(SSL)"

[toml]
name = "TOML"
desc = "Tom's Obvious, Minimal Language"

[tds]
name = "TDS"
desc = "Tabular Data Stream"

[tps]
name = "TPS"
desc = "Transactions Per Second"

[ttf]
name = ".ttf"
desc = "TrueType Font"
see = ["otf"]

[tiobe]
name = "TIOBE"
desc = "The Importance of Being Earnest"

[tldp]
name = "TLDP"
desc = "Linux Documentation Project"

[tcc]
name = "TCC"
desc = "Tiny C Compiler"

[tg]
name = "TG"
desc = "Telegram"

[toc]
name = "ToC"
desc = "Table of Contents"

[tpu]
name = "TPU"
desc = "Tensor Processing Unit"

[tcp]
name = "TCP"
desc = "Transmission Control Protocol"
see = ['UDP', 'IP']

[tag]
name = "TAG"
desc = "Tree-adjoining Grammar"
see = ['PEG', 'CFG']

[ttl]
name = "TTL"
desc = "Transistorâ€“Transistor Logic"

[tmg]
name = "TMG compiler-compiler"
desc = "TransMoGrifier"
full = "A recursive descent compiler-compiler developed by Robert M. McClure and presented in 1965"
see = ['Yacc']

[tty.coreutils]
name = "tty (coreutils) "
desc = "teletype"
full = "Print terminal name"

[tch]
name = "tcsh"
desc = "TENEX C Shell"

[tdd]
name = "TDD"
desc = "Test-driven development"

[tgmath.Cheader]
name = "<tgmath.h>"
desc = "Type-generic math"

[tui]
name = "TUI"
desc = "Text-based User Interface"
