[tiff]
disp = "TIFF"
desc = "Tag Image File Format"

[ti]
disp = "TI"
desc = "Texas Instruments"

[tsv]
disp = "TSV"
desc = "Tab-separated values"

[tsx]
disp = "TSX"
desc = "Transactional Synchronization Extensions"

[tls]
disp = "TLS"
desc = "Transport Layer Security"

[toml]
disp = "TOML"
desc = "Tom's Obvious, Minimal Language"

[tds]
disp = "TDS"
desc = "Tabular Data Stream"

[tps]
disp = "TPS"
desc = "Transactions Per Second"

[ttf]
disp = ".ttf"
desc = "TrueType Font"
see = ["otf"]

[tiobe]
disp = "TIOBE"
desc = "The Importance of Being Earnest"

[tldp]
disp = "TLDP"
desc = "Linux Documentation Project"
