[utc]
disp = "UTC"
desc = "Universal Time Coordinated"

[uac]
disp = "UAC"
desc = "User Account Control(Windows)"

[uri]
disp = "URI"
desc = "Uniform Resource Identifier"

[uiop]
disp = "UIOP"
desc = "Utilities for Implementation- and OS- Portability"
full = "Common Lisp's ASDF's library"

[uuid]
disp = "UUID"
desc = "Universally Unique Identifier"

[ucrt]
disp = "UCRT"
desc = "Universal C Runtime Library by Windows"

[unicode]
disp = "Unicode"
desc = "Universal Coded Character Set"

[utf]
disp = "UTF"
desc = "Unicode Transformation Format"
see = ["Unicode"]

[ucs]
disp = "UCS"
desc = "Universal Character Set"

[ufcs]
disp = "UFCS"
desc = "Uniform Function Call Syntax in Dlang"

[usb]
disp = "USB"
desc = "Universal Serial Bus"

[uefi]
disp = "UEFI"
desc = "Unified Extensible Firmware Interface"

[uart]
disp = "UART"
desc = "Universal Asynchronous Serial port"

[uml]
disp = "UML"
desc = "Unified Modeling Language"
