[utc]
name = "UTC"
desc = "Universal Time Coordinated"

[uac]
name = "UAC"
desc = "User Account Control(Windows)"

[uri]
name = "URI"
desc = "Uniform Resource Identifier"

[uiop]
name = "UIOP"
desc = "Utilities for Implementation- and OS- Portability"
more = "Common Lisp's ASDF's library"

[uuid]
name = "UUID"
desc = "Universally Unique Identifier"

[ucrt]
name = "UCRT"
desc = "Universal C Runtime Library by Windows"

[unicode]
name = "Unicode"
desc = "Universal Coded Character Set"

[utf]
name = "UTF"
desc = "Unicode Transformation Format"
see = ["Unicode"]

[ucs]
name = "UCS"
desc = "Universal Character Set"

[ufcs]
name = "UFCS"
desc = "Uniform Function Call Syntax in Dlang"

[usb]
name = "USB"
desc = "Universal Serial Bus"

[uefi]
name = "UEFI"
desc = "Unified Extensible Firmware Interface"

[uart]
name = "UART"
desc = "Universal Asynchronous Serial port"

[uml]
name = "UML"
desc = "Unified Modeling Language"

[udp]
name = "UDP"
desc = "User Datagram Protocol"

[unix]
name = "Unix"
desc = "Uniplexed Information and Computing Service"
see = ['Multics']

[ufw]
name = "UFW"
desc = "Uncomplicated FireWall"
more = "A frontend for managing firewall rules in Arch Linux, Debian, or Ubuntu"

[usi]
name = "USI"
desc = "Universal Stylus Initiative"

[uwp]
name = "UWP"
desc = "Universal Windows Platform"

[usim]
name = "USIM card"
desc = "Universal Subscriber Identity Module"
