[utc]
disp = "UTC"
desc = "Universal Time Coordinated"

[uac]
disp = "UAC"
desc = "User Account Control(Windows)"

[uri]
disp = "URI"
desc = "Uniform Resource Identifier"

[uiop]
disp = "UIOP"
desc = "Utilities for Implementation- and OS- Portability"
full = "Common Lisp's ASDF's library"

[uuid]
disp = "UUID"
desc = "Universally Unique Identifier"
