[vim]
name = "Vim"
desc = "Vi improved"
see = ["Emacs"]

[vsz]
name = "VSZ"
desc = "Virtual Set Size"
more = "It includes all memory that the process can access, including memory that is swapped out, memory that is allocated, but not used, and memory that is from shared libraries."
see = ['RSS']

[vr]
name = "VR"
desc = "Virtual Reality"
see = ["AR"]

[vsdx]
name = ".vsdx"
desc = "Visio drawing"

[vlsi]
name = "VLSI"
desc = "Very Large Scale Integration"

[vhdl]
name = "VHDL"
desc = "VHSIC Hardware Description Language"
see = ['VHSIC', 'HDL']

[vhsic]
name = "VHSIC"
desc = "Very High-Speed Integrated Circuits Program"
see = ['VHDL']

[vcs]
name = "VCS"
desc = "Version Control System"

[vs]
name = "VS"
desc = "Visual Studio"

[vpc]
name = "VPC"
desc = "Virtual Private Cloud"

[vps]
name = "VPS"
desc = "Virtual Private Server"

[vpn]
name = "VPN"
desc = "Virtual Private Network"

[vnc]
name = "VNC"
desc = "Virtual Network Computing"
more = "A graphical desktop-sharing system that uses the Remote Frame Buffer protocol (RFB) to remotely control another computer. "

[vc.version]
name = "VC"
desc = "Version Control"

[vax]
name = "VAX"
desc = "Virtual Address eXtension"
more = "By DEC, one of the most successful minicomputers in history. Featuring a 32-bit ISA and virtual memory, was seen as a 32-bit extension of the older 16-bit PDP-11"
see = ['VMS']

[vms]
name = "VMS"
desc = "Virtual Memory System"
more = "a multi-user, multiprocessing and virtual memory-based operating system announced by DEC alongside the VAX-11/780 minicomputer in 1977"
see = ['VAX']

[vdso]
name = "vDSO"
desc = "virtual dynamic shared object"
more = "A kernel mechanism for exporting a carefully selected set of kernel space routines to user space applications so that applications can call these kernel space routines in-process, without incurring the performance penalty of a mode switch from user mode to kernel mode that is inherent when calling these same kernel space routines by means of the system call interface"

[vp9]
name = "VP9"
desc = "An open and royalty-free video coding format developed by Google"
more = "It's the successor to VP8 and competes mainly with MPEG's High Efficiency Video Coding (HEVC/H.265)"
see = ['AV1', 'HEVC']

[vte]
name = "VTE"
desc = "GTK widget: Virtual Terminal Emulator"

[vma]
name = "VMA"
desc = "Virtual Memory Area"

[vdi]
name = ".vdi"
desc = "VirtualBox Disk Image"
see = ['vmdk', 'qcow']

[vhd]
name = ".vhd"
desc = "Virtual Hard Disk"

[vmdk]
name = "VMDK"
desc = "Virtual Machine Disk"
more = "A file format that describes containers for virtual hard disk drives to be used in virtual machines like VMware Workstation or VirtualBox"
see = ['vdi', 'qcow']

[vdi.Desktop]
name = "VDI"
desc = "Virtual Desktop Infrastructure"

[vlc]
name = "VLC media player"
desc = "VideoLAN Client"

[vcr]
name = "VCR"
desc = "Videocassette Recorder"

[va-api]
name = "VA-API"
desc=  "Video Acceleration API by Intel"

[vga]
name = "VGA"
desc = "Video Graphics Array"
more = "A video display controller and accompanying de facto graphics standard, first introduced with the IBM PS/2 line of computers in 1987"

[vlan]
name = "VLAN"
desc = "Virtual Local Area Network"

[vla]
name = "VLA"
desc = "Variable Length Arrays"

[vnd]
name = "vnd"
desc = "vendor"
