[wpa]
disp = "WPA"
desc = "Wi-Fi Protected Access"

[waf]
disp = "WAF"
desc = "Web Application Firewall"

[webp]
disp = "WebP"
desc = "Photo format for the Web"
full = "Announced in 2010 by Google. A modern image format that provides superior lossless and lossy compression for images on the web"

[webm]
disp = "WebM"
desc = "Media format for the Web"
full = "Sponsored by Google. Intended to offer a royalty-free alternative to use in the HTML5 video and the HTML5 audio elements"

[wmi]
disp = "WMI"
desc = "Windows Management Instrumentation"
full = "it's deprecated, use CIM instead"
see = ['CIM']

[wapi]
disp = "WAPI"
desc = "WLAN Authentication and Privacy Infrastructure"

[wpc]
disp = "WPC"
desc = "Wireless Power Consortium"

[wasi]
disp = "WASI"
desc = "WebAssembly System Interface"

[wchar]
disp = "wchar"
desc = "wide character"
