[xdm.Download]
name = "XDM"
desc = "eXtreme Download Manager"

[xdm.Display]
name = "XDM"
desc = "X Display Manager"

[xdg]
name = "XDG"
desc = "Cross Desktop Group"

[xxd]
name = "xxd"
desc = "hex file dump"
more = "Why call this 'xxd' rather than 'xd' ??"

[xkcd]
name = "xkcd"
desc = "a webcomic created in 2005 by American author Randall Munroe"
more = "It's not actually an acronym. It's just a word with no phonetic pronunciation -- a treasured and carefully-guarded point in the space of four-character strings."

[xml]
name = "XML"
desc = "Extensible Markup Language"

[xslt]
name = "XSLT"
desc = "Extensible Stylesheet Language Transformations"

[xpm]
name = "XPM"
desc = "X PixMap"
more = "An image file format used by the X Window System, created in 1989"

[xss]
name = "XSS"
desc = "Cross-site Scripting"

[xul]
name = "XUL"
desc = "XML User Interface Language"
more = "An XML dialect for writing graphical user interfaces developed by Mozilla"

["x.509"]
name = "X.509"
desc = "an ITU standard defining the format of public key certificates"

[xcoff]
name = "XCOFF"
desc = "eXtended COFF"
more = "An improved and expanded version of the COFF object file format defined by IBM and used in AIX. Early versions of the PowerPC Macintosh also supported XCOFF, as did BeOS."
see = ['COFF']

[xmpp]
name = "XMPP"
desc = "Extensible Messaging and Presence Protocol"

[xhtml]
name = "XHTML"
desc = "Extensible HyperText Markup Language"

[xls.Office]
name = "XLS"
desc = "Excel Spreadsheet"

[xsd.XML]
name = "XSD"
desc = "XML Schema Definition"

[xpath.XML]
name = "XPath"
desc = "XML Path Language"
more = "An expression language designed to support the query or transformation of XML documents."

[xdmcp]
name = "XDMCP"
desc = "X Display Manager Control Protocol"

[xr]
name = "XR"
desc = "Extended Reality"
see = ['AR', 'VR']

[xt]
name = "IBM XT"
desc = "IBM PC eXtended Technology"
see = ['AT', 'PS/2']

[xhr]
name = "XHR"
desc = "XMLHttpRequest"

[xcf]
name = "XCF"
desc = "eXperimental Computing Facility"
more = "The native image format of the GIMP image-editing program. It saves all of the data the program handles related to the image, including, among others, each layer, the current selection, channels, transparency, paths and guides"

[xmp]
name = "XMP"
desc = "Extensible Metadata Platform"
more = """An ISO standard, originally created by Adobe Systems Inc., for the creation, processing and interchange of standardized and custom metadata for digital documents and data sets.
  XMP standardizes a data model, a serialization format and core properties for the definition and processing of extensible metadata. It also provides guidelines for embedding XMP information into popular image, video and document file formats, such as JPEG and PDF, without breaking their readability by applications that do not support XMP
"""
